html-symbol-entities/README.md
- Improve spelling of the instructions.
- Improve readability of the text.
=> docs(html-symbol-entities) improve instructions

README.md
- Improve readability of the instructions.
- Add missing links to related tools.
=> docs(README.md) improve instructions

pull-changes-from-upstream.sh
- Add tool to merge latest changes from the upstream Git repository
Related to the https://github.com/Jason-Rev/vscode-spell-checker/pull/121 pull request.
=> feat(pull-changes-from-upstream.sh) new tool

README.md, ca/README.md
Plus I effed up the GPLv2 license line, now it looks a bit better
=> I kind of forgot to update the README

python/cspell-ext.json
Fixes Jason-Rev/vscode-spell-checker#161
=> Ignore regex for F-Strings

README.md, generator-cspell-dicts/README.md, packages/ca/README.md, packages/golang/README.md
- Improve consistency of the documents
=> style(docs): improve document structure

packages/companies/companies.txt
Part of https://github.com/Jason-Rev/vscode-spell-checker/issues/258 , PR moved from https://github.com/Jason3S/cspell/pull/74
=> Add Wacom to companies list

packages/cpp/cpp.txt
I didn't go through the list, these are just a few that i have run into recently
=> cpp: Remove typos

packages/en_GB/wordsEnGb.txt
They are already present in American English dictionary
=> Added rollback and rollbacks to to British English dictionary

packages/cpp/cpp.txt
Few more i've tripped up on. I didn't rebuild the tar since I figured that would be something you'd  do as part of a release
=> remove CPP typos

packages/cpp/cpp.txt
=> fix(cpp): Remove intialized

packages/companies/companies.txt, packages/fullstack/fullstack.txt
=> enhance - fullstack, companies : add words

packages/elixir/elixir.txt
Hey, I went ahead and updated the elixir dictionary with some more words that are commonly
found in an elixir project.
=> Update elixir dict

packages/companies/companies.txt
I noticed that you have a companies dictionary, so I added the company that I work for to the list https://cyon.ch
=> Add cyon to the list of companies

packages/companies/companies.txt, packages/companies/package-lock.json
Improvements to the `cspell-dict-companies` dictionary.
- Update outdated `package-lock.json` for `cspell-dict-companies`
- Improve dictionary list order
- Use `Sort Lines Ascending` feature from VS Code
- Add new companies to the list
- Improve dictionary list order
- Use `Sort Lines Ascending` feature from VS Code
=> Improvements to the `cspell-dict-companies` dictionary

packages/companies/companies.txt
=> Add Kabbage to companies dictionary

README.md, packages/fr_FR_90/CHANGELOG.md, packages/fr_FR_90/LICENSE, packages/fr_FR_90/README.md, packages/fr_FR_90/cspell-ext.json, packages/fr_FR_90/index.d.ts, packages/fr_FR_90/index.js, packages/fr_FR_90/link.js, packages/fr_FR_90/package-lock.json, packages/fr_FR_90/package.json, packages/fr_FR_90/unlink.js, packages/fr_FR_90/util.js
I didn't manage to test the dictionary, maybe I didn't fill the YO fields the good way, I don't know... 
I think I should have made a draft PR because it seems to be merging as is...
=> add fr_FR_90 Français Réforme 1990 dictionary

packages/da_DK/cspell-ext.json
Remove the unnecessary include filtering.
=> Fix spelling checking with Danish dictionary.

packages/companies/companies.txt
=> Added KUKA to companies dictionary

README.md
Update link to LangaugeIds - previous link was a 404
=> Fix link to LanguageIds

packages/companies/companies.txt
[Mattermost](https://mattermost.com), one of Y Combinator’s top 100 companies, provides an open source enterprise-grade messaging platform to the world’s leading organizations that allows teams to collaborate securely and privately anywhere.
=> Add Mattermost

packages/software-terms/softwareTerms.txt
Add autolink and its variants (autolinked, autolinking)
=> Add autolink and its variants

packages/software-terms/softwareTerms.txt
=> Add gravatar & gravatars

packages/latex/latex.txt
This PR adds a few latex commands (built-in and from the biblatex package).
=> Add a few more latex commands

packages/cpp/cspell-ext.json
Use Patterns instead of raw regexp.
=> fix: define patterns for ignoreRegExpList

packages/en_GB/wordsEnGb.txt, packages/en_US/src/en_US.txt
This adds the dictionary equivalents of misogyny for misandry.
=> Add misandry/misandrist

scripts/pull-changes-from-upstream.sh
This is something better handled by contributor's git alias'
=> chore: Remove pull changes script

packages/html/html.txt, packages/html/package.json
=> ci: prepare publish html dictionary

packages/companies/companies.txt
source: https://en.wikipedia.org/wiki/Information_technology_in_Russia
=> add russian it companies

packages/software-terms/softwareTerms.txt
See https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it
=> Add "YAGNI"

packages/csharp/cspell-ext.json, packages/csharp/cspell.json, packages/csharp/samples/verbatim.cs
=> fix: define c# strings

dictionaries/fonts/fonts.txt
=> added Japanese font name to fonts.txt

dictionaries/software-terms/softwareTerms.txt
=> Add scrollable

dictionaries/ada/cspell-ext.json, package.json, packages/ada/cspell.json, packages/ada/package.json, yarn.lock
Add `"globRoot": "${cwd}"` so the overrides will work.
=> fix: fix Ada overrides

dictionaries/ruby/ruby.txt
I added some ruby/rails keywords that were giving me squigglies. Please let me know if this is the correct way to contribute these, and whether or not this type of contribution is welcome. If so, I will probably be contributing similar things in the future!
=> Add some keywords to ruby dict

dictionaries/python/python.txt
https://docs.python.org/3/library/argparse.html#the-add-argument-method
=> [Python] Adds nargs from argparse

dictionaries/software-terms/softwareTerms.txt
=> feat: add allowlist, denylist to software terms

dictionaries/fullstack/fullstack.txt
=> Add 'opentype' to fullstack dict

dictionaries/npm/npm.txt
See https://yarnpkg.com/advanced/pnpify#ide-support.
=> Add "pnpify," "sdks," and "yarnpkg" to npm dict.

dictionaries/filetypes/filetypes.txt
Add "appxmanifest," "editorconfig," "gitattributes", and "jscpd."
=> Add a few words to the file types dictionary.

dictionaries/bash/bash-words.txt
These are popular bash linters.
=> Add "shellcheck" and "shfmt" to bash dictionary.

dictionaries/software-terms/softwareTerms.txt
asm, cvss, destructured, gitlab, isc, mixins, mpl, musl, osi, spdx, wasm.
Most refer to licensing, also a few compilation targets, OOP pattern, security and a popular git hosting service.
=> Add various software-terms

dictionaries/software-terms/softwareTerms.txt
Add "gitlens" and "vsliveshare."
=> Add some VSCode extensions to software terms dict.

dictionaries/powershell/powershell.txt
Add "ERRORLEVEL," "findstr," "popd," "pushd," and "USERPROFILE."
=> Add some terms to powershell dictionary.

dictionaries/en_GB/src/additional_words.txt
```
Alpha Centauri
amphitheatre
Christoph
COVID
eligibilities
hmmm
iPads
unintuitive
```
=> Add several terms

dictionaries/python/python.txt
Adds `numpy` to they python dictionary
=> Adds `numpy`

dictionaries/companies/companies.txt
Proposes adding the following companies:
```
Appetize
Bitly
Experian
Figma
Hipercard
JFrog
LinkedIn
Lyft
NordVPN
Paylocity
Zillow
```
=> Add additional companies

dictionaries/companies/companies.txt
Adds Freshworks to the companies dictionary
=> add Freshworks to companies

dictionaries/dotnet/dotnet.txt
This is the name of a popular Visual Studio extension for .NET.
=> Add "ReSharper" to dotnet dictionary.

dictionaries/npm/npm.txt
"yarnrc" is the name of the Yarn configuration file.
=> Add "yarnrc" to npm dictionary.

package.json, yarn.lock
Related to: [Security: Upgrade meow · Issue #672 · yeoman/yo](https://github.com/yeoman/yo/issues/672)
=> fix: force update of `meow` to `^9.0.0`

dictionaries/en_US/src/additional_words.txt
https://www.merriam-webster.com/dictionary/multiline
https://en.wiktionary.org/wiki/multiline
=> add multiline

dictionaries/en_GB/src/additional_words.txt
https://www.merriam-webster.com/dictionary/reauthenticate
https://en.wiktionary.org/wiki/reauthenticate
=> add reauthenticate

dictionaries/python/python.txt
Add "commitizen," "getenv," and "pyproject."
=> Add some terms to Python dictionary.

dictionaries/software-terms/softwareTerms.txt
Add "blocklint," "mailmap," and "maxkb."
=> Add some terms to software terms dictionary.

dictionaries/python/python.txt
These are both well-established linters.
=> Add "autopep" and "docformatter" to Python dict.

dictionaries/ru_RU/README.md
https://www.npmjs.com/package/@cspell/dict-ru_ru
=> fix npm module name

dictionaries/software-terms/src/software-terms.txt
Docker offers rootless and "rootful" modes:
https://docs.docker.com/engine/security/rootless/.
=> Add "rootful" to software terms dictionary.

dictionaries/software-terms/src/software-tools.txt
Add "asdf," "Secretlint," and "secretlintignore."
=> Add some terms to software tools dictionary.

dictionaries/software-terms/src/software-terms.txt
[What does netloc mean? | Newbedev](https://newbedev.com/what-does-netloc-mean)
=> fix: add `netloc`

dictionaries/fullstack/cspell-ext.json
Use the fullstack dictionary with more languages.
=> fullstack: Match more languages

dictionaries/software-terms/src/software-terms.txt
Added "uncomment" and forms to US and GB dicts,
as per https://en.wiktionary.org/wiki/uncomment
and google:
=> Add words: uncomment, uncommented, uncommenting, uncomments

dictionaries/software-terms/src/software-tools.txt
Actionlint is a linter for GitHub Actions.
=> Add "Actionlint" to software tools dictionary.

dictionaries/bash/bash-words.txt
This is the name of an Aptitude package manager utility.
=> Add "autoremove" to Bash dictionary.

dictionaries/html/html.txt, dictionaries/html/package.json
=> fix: Make HTML dictionary case sensitive

dictionaries/software-terms/src/software-terms.txt
Related to
- [PBKDF2 - Wikipedia](https://en.wikipedia.org/wiki/PBKDF2)
- [bcrypt - Wikipedia](https://en.wikipedia.org/wiki/Bcrypt)
- [scrypt - Wikipedia](https://en.wikipedia.org/wiki/Scrypt)
=> fix (software-terms): Add some encryption terms.

dictionaries/software-terms/src/software-terms.txt
Parts of the alphabet are commonly used in testing.
=> fix: Add the parts of the alphabet

dictionaries/bash/bash-words.txt
=> Add some commands

dictionaries/r/samples/base.r, dictionaries/r/samples/grDevices.r, dictionaries/r/samples/graphics.r, dictionaries/r/samples/stats.r
Here are samples for R taken from the demos of the default packages, as requested [here](https://github.com/streetsidesoftware/cspell-dicts/pull/871#issuecomment-1027192797).
=> test: add r samples

dictionaries/python/python.txt
Found a few python words to add.  
1 method
1 object
5 libraries
=> Add python words

dictionaries/software-terms/src/software-tools.txt
This adds PyCharm to software tools.
=> Add pycharm to software tools

dictionaries/bash/bash-words.txt
=> Add mkdir to bash-words

dictionaries/en_GB/package.json, dictionaries/en_GB/src/aoo-mozilla-en-dict/README_en_GB.txt, dictionaries/en_GB/src/aoo-mozilla-en-dict/en-GB.aff, dictionaries/en_GB/src/aoo-mozilla-en-dict/en-GB.dic, dictionaries/en_US/package.json
Ensure the dictionaries get copied to the right place.
=> ci: fix cpy behavior change.

dictionaries/software-terms/src/network-os.txt, dictionaries/software-terms/src/network-protocols.txt
Add 1 network protocol and  2 os
=> Add 1 network protocol and 2 os

dictionaries/companies/src/companies.txt
Adds [Fireblocks](https://www.fireblocks.com/) to the list of companies
=> Add Fireblocks to companies.txt

dictionaries/dotnet/dotnet.txt
Add "FormattableString," "FormattableStringFactory," and "IFormattable."
=> Add some terms to dotnet dictionary.

dictionaries/cpp/cpp.txt
Noticed a bad suggestion "implementaiton" and say a few nearby suspect ones
=> fix: more cpp typos

dictionaries/node/additional_words.txt
Automock is a Jest config setting.
=> Add "automock" to Node dictionary.

dictionaries/en_US/src/additional_words.txt
=> fix: Add Kyiv

dictionaries/cpp/package.json, dictionaries/csharp/package.json, dictionaries/golang/package.json, dictionaries/html-symbol-entities/package.json, dictionaries/python/package.json, yarn.lock
Lerna is a bit broken, so force a major version by hand.
=> fix: Force major version

dictionaries/companies/src/companies.txt
Added Bloomreach, Inc., Responsys & Twilio
=> added a few additional companies

dictionaries/en_US/src/additional_words.txt
it basically conveys no useful information
=> make pointless header more explicit

dictionaries/software-terms/src/software-tools.txt
See https://github.com/primer/octicons.
=> Add "Octicons" to software tools dictionary

dictionaries/latex/cspell-ext.json, dictionaries/latex/cspell.json
=> fix: Fix false positive LaTeX Math matching

dictionaries/latex/cspell-ext.json, dictionaries/latex/samples/issue-1097.tex
This is a partial fix for #1097
=> fix: #1097

dictionaries/python/scripts/extractLib.py, dictionaries/python/src/python/python-lib.txt
Related to #1099 and https://github.com/streetsidesoftware/cspell-dicts/pull/1042#issuecomment-1133544778
=> fix: Add Python Lib terms from `__init__.py`

dictionaries/software-terms/src/software-terms.txt
Add "ref," "reference," and "refname."
=> Add some ref-related words to software terms dict

dictionaries/npm/npm.txt
Adding Vitejs and Vitest into the npm packages
=> Update npm.txt with Vitejs and Vitest package names

dictionaries/fullstack/fullstack.txt
* [keyvalue](https://angular.io/api/common/KeyValuePipe)
* [nosnippet](https://searchengineland.com/google-explains-the-noindex-nofollow-noarchive-nosnippet-meta-tags-10595)
* [upsert](https://fr.wiktionary.org/wiki/upsert#:~:text=Mot%2Dvalise%20de%20update%20et,%C3%A0%20jour%20et%20ins%C3%A9rer%20%C2%BB)
* [wysiwyg](https://fr.wikipedia.org/wiki/What_you_see_is_what_you_get)
=> fix: Add words to fullstack dictionary

dictionaries/companies/src/companies.txt
added `mozilla` to `companies` dictionary
=> [companies] mozilla

dictionaries/java/java.txt
Add "testcase," "testsuite," and "testsuites."
=> Add some JUnit terms to Java dictionary

dictionaries/en_US/src/additional_words.txt
=> Add `draggable` to en-US

dictionaries/software-terms/src/software-terms.txt
This is the name of a recently added argument to mega-linter-runner.
=> Add "containername" to software-terms dictionary

dictionaries/software-terms/src/software-terms.txt
"deps" is short for "dependencies."
=> Add "deps" to software terms dictionary.

dictionaries/companies/src/companies.txt
Add the Instagram company name
=> Update companies.txt - Add Instagram

dictionaries/bash/bash-words.txt
Add "dbus," "newgidmap," "newuidmap," and "uidmap."
=> Add some terms to Bash dictionary

dictionaries/typescript/example/cspell-node.config.js, dictionaries/typescript/example/readPackageInfo.js, dictionaries/typescript/example/run.js
Example of a dictionary based upon package names.
=> doc: Example package-name dictionary

dictionaries/en_GB/src/additional_words.txt, dictionaries/en_US/src/additional_words.txt
fix https://github.com/streetsidesoftware/cspell-dicts/issues/1253
=> feat: add guillemet to en_GB and en_US

dictionaries/npm/npm.txt, dictionaries/software-terms/src/software-terms.txt
=> feat: add ulid

dictionaries/ada/cspell-ext.json, dictionaries/ada/cspell.json, dictionaries/ada/package.json, dictionaries/ada/samples/issue-1276/test.adb
=> fix: support English contractions in Ada files.

dictionaries/cpp/src/compiler-gcc.txt, dictionaries/cpp/src/ecosystem.txt, dictionaries/cpp/src/lang-keywords.txt, dictionaries/cpp/src/stdlib-c.txt, dictionaries/cpp/src/stdlib-cpp.txt
- added some missing standard-library things
- added some names of common tools in the ecosystem and their related commands
- added some names of common non-standard libraries
=> fix: [cpp-refined] updates

dictionaries/ar/cspell-ext.json
=> fix: Arabic - Ignore certain accents

dictionaries/companies/src/companies.txt
Added the following:
1. Mockito
2. Yext
=> fix: `Mockito` and `Yext` to Companies

dictionaries/software-terms/src/software-tools.txt
=> fix: add `launchdarkly` to software-tools.txt

dictionaries/npm/npm.txt
browserslist from https://www.npmjs.com/package/browserslist
=> fix: add `browserslist` to npm.txt

dictionaries/en_GB/src/wordsEnGb.txt
https://en.wikipedia.org/wiki/%C3%85land
https://en.wikipedia.org/wiki/Ivory_Coast (Côte d'Ivoire)
https://en.wikipedia.org/wiki/Svalbard_and_Jan_Mayen
https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe
=> fix: add some country names

dictionaries/npm/npm.txt
https://www.npmjs.com/package/jszip
=> fix: add `jszip` npm.txt

dictionaries/npm/npm.txt
https://www.npmjs.com/package/react-dropzone
=> fix: add `dropzone` to npm.txt

dictionaries/companies/src/companies.txt
=> fix: add `Swyftx` to Companies

dictionaries/html/html.txt
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API
=> Add gamepad api events

dictionaries/ar/package.json, dictionaries/de_CH/package.json, dictionaries/de_DE/package.json, dictionaries/en_GB-MIT/package.json, dictionaries/en_GB/package.json, dictionaries/en_US/package.json, dictionaries/es_ES/package.json, dictionaries/et-EE/package.json, dictionaries/fr_FR/package.json, dictionaries/fr_FR_90/package.json, dictionaries/nl_NL/package.json, dictionaries/pt_BR/package.json, dictionaries/ru_RU/package.json, dictionaries/sl_SI/package.json, dictionaries/sv/package.json
Make sure `*.trie.gz` can be updated.
=> chore: force overwrite in prepare

dictionaries/html/html.txt
Dictionary: HTML
Added a new entry for the nobr tag
=> fix: added `nobr` entry

dictionaries/fonts/fonts.txt
Pulled from https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list
=> feat: sync Windows 10 font list

dictionaries/lorem-ipsum/dictionary.txt
Dictionary: lorem-ipsum
This is a well-known typeface test word.
https://en.wikipedia.org/wiki/Hamburgevons
=> Add hamburgevons

dictionaries/en_US/src/additional_words.txt
XXXL seems to belong here, since XXL is already included.
http://app.aspell.net/lookup?dict=en_US;words=extremum
http://app.aspell.net/lookup?dict=en_US;words=pangram
http://app.aspell.net/lookup?dict=en_US;words=rasterize
http://app.aspell.net/lookup?dict=en_US;words=xxxl
=> Add some English words

.githooks/commit-msg, .githooks/pre-commit, cspell-dict-file-checker/package.json, yarn.lock
See: https://github.com/avajs/ava/issues/3093
=> ci: fix ava fault on node 18.8.0

package.json, yarn.lock
Since `lerna` is mainly used for publishing, `lerna-lite` is a better fit.
=> chore: switch to lerna-lite

dictionaries/css/css.txt
=> feat: add CSS values from mdn-browser-compat

dictionaries/html/html.txt
=> feat: add words from HTML mdn-browser-compat

dictionaries/companies/src/companies.txt
Add Mondoo (mondoo.com) and move SmartyStreets here. It was previously
in the software section which is wrong and I'll remove that in another
PR
Signed-off-by: Tim Smith <tsmith84@gmail.com>
=> fix: Add new companies

dictionaries/companies/src/companies.txt
Dictionary: Companies
Add `fastlane`
https://fastlane.tools/
=> fix: add `fastlane` to `companies.txt`

dictionaries/companies/src/companies.txt, dictionaries/software-terms/src/software-tools.txt
=> fix: Add Grafana to companies.txt

dictionaries/software-terms/src/software-terms.txt
add the new `neumorphism` word
- https://css-tricks.com/neumorphism-and-css/
=> fix: add neumorphism to software terms

dictionaries/es_ES/src/additional_words.txt
Dictionary: es_ES
Add `colecionable` and `monitorear` words.
- https://dle.rae.es/coleccionable
- https://dle.rae.es/monitorear
=> Update additional_words.txt (Spanish)

dictionaries/software-terms/src/software-terms.txt
add encodable to software-terms
- [Encodable - definition of encodable by The Free Dictionary](https://www.thefreedictionary.com/encodable)
- [Encodable | Apple Developer Documentation](https://developer.apple.com/documentation/swift/encodable)
=> fix: add encodable to software-terms

dictionaries/npm/npm.txt
Add posthtml
https://www.npmjs.com/package/posthtml
https://posthtml.org/#/packages
=> fix: Add posthtml

dictionaries/software-terms/src/software-terms.txt
http://app.aspell.net/lookup?dict=en_US;words=incrementable
https://en.wiktionary.org/wiki/incrementable
=> fix: Add incrementable

dictionaries/software-terms/src/software-terms.txt
_Adding Microservices to Software Terms_
- https://microservices.io/
- https://aws.amazon.com/microservices/
=> fix: Add microservices to software

dictionaries/npm/npm.txt
Add discordjs - https://www.npmjs.com/package/@discordjs/builders
Add iamtraction - https://www.npmjs.com/package/@iamtraction/google-translate
Add twmoji - https://www.npmjs.com/package/twemoji-parser
- See above
=> fix: Add some package names to npm

dictionaries/cryptocurrencies/cryptocurrencies.txt
Dictionary: cryptocurrencies
Add `huobi` and `orderbook`
- https://www.huobi.com/
- https://en.wikipedia.org/wiki/Order_book
=> fix: Add `huobi` and `orderbook`

dictionaries/de_DE/cspell-tools.config.yaml, dictionaries/en_US/cspell-tools.config.yaml, package.json, yarn.lock
Until cspell-tools has stabilized, lock the version.
=> chore: lock cspell-tools version

dictionaries/companies/src/companies.txt
Dictionary: Companies
Added following companies
Plex - https://www.plex.tv/
Trakt - https://trakt.tv/
Letterboxd - https://letterboxd.com/
See above
=> fix: Add companies

dictionaries/en_GB/README.md
Force a major version since the dictionary was rebuilt.
=> feat!: Force major version for en_GB.

dictionaries/companies/src/companies.txt, dictionaries/docker/src/docker-words.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: Companies, Software tools, Docker
Added Portainer 
https://portainer.io 
=> fix: Add Portainer

.gitignore, generator-cspell-dicts/generators/app/index.js, generator-cspell-dicts/generators/app/templates/cspell-ext.json, generator-cspell-dicts/generators/app/templates/cspell-tools.config.yaml, generator-cspell-dicts/generators/app/templates/package.json, generator-cspell-dicts/package.json, package.json, yarn.lock
Improve the create dictionary script.
=> fix: Improve dictionary generation

dictionaries/html/src/html.txt
Dictionary: html
Add playsinline
- [what-does-playsinline-mean-in-web-video](https://css-tricks.com/what-does-playsinline-mean-in-web-video/)
- [MDN video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-playsinline)
=> fix: add - html.txt : playsinline

dictionaries/en_US/src/additional_words.txt
Related to: #1622 
Add `Aruban` and `Arubans`
- See: https://en.wikipedia.org/wiki/Aruba
=> fix: Add Aruban to en_US dictionary.

cSpell.json, dictionaries/en_GB-MIT/source-dependencies.txt, dictionaries/en_GB-MIT/src/additional_words.txt, dictionaries/en_GB-MIT/src/shared-additional-words.txt, dictionaries/en_GB/source-files.txt, dictionaries/en_GB/src/shared-additional-words.txt, dictionaries/en_US/README.md, dictionaries/en_US/source-files.txt, dictionaries/en_US/src/additional_words.txt, dictionaries/en_US/src/shared-additional-words.txt, shared-sources/en/shared-additional-words.txt
Dictionary: en_US and en_GB
Make it easier to share common words between the dictionaries.
=> feat: Share words between all English dictionaries.

shared-sources/en/shared-additional-words.txt
Dictionary: en
Add English term `hyponym`
- [hyponym - Wiktionary](https://en.wiktionary.org/wiki/hyponym)
=> fix: Add hyponym

dictionaries/companies/dict/companies.txt, dictionaries/companies/src/companies.txt
Dictionary: _companies_
Added Steelers to dictionary per #1689 
- [Pittsburgh Steelers](https://steelers.com)
- [ ✅] By submitting this issue, you agree to follow our
=> fix: Add Pittsburgh Steelers to Companies

dictionaries/npm/src/npm.txt
Add `sveltekit` to npm package list
=> fix: Add `sveltekit` to npm package list

shared-sources/en/shared-additional-words.txt
Dictionary: `shared-sources/en/shared-additional-words.txt`
Add `prerequire`
[collinsdictionary](https://www.collinsdictionary.com/dictionary/english/prerequire)
=> fix: Add `prerequire` to `en/shared-additional-words.txt`

dictionaries/npm/src/npm.txt
Dictionary: `npm`
Add `globby` and `fast-glob` to NPM package list.
=> fix: Add globby to known `npm` packages

dictionaries/en_shared/src/shared-additional-words.txt
Happy to have this PR rejected if these are considered as strictly hyphenated words.
- Dictionary: `en-shared.txt`
- add `pregenerate` and `pregenerated`
- https://en.wiktionary.org/wiki/pregenerated
=> fix: add `pregenerate+d` to en-shared.txt

README.md
Dictionary: NA
Add K8s to list of all dictionaries
NA
=> docs: Add K8s to list of Dictionaries

dictionaries/ruby/src/ruby.txt
Dictionary: ruby
Adding various Ruby terms.
See commented lines.
=> fix: Add some more Ruby terms

dictionaries/companies/src/companies.txt, dictionaries/software-terms/src/software-services.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: 
Software Terms
Companies
- [Appointedd](https://www.appointedd.com/)
- [Calendly](https://calendly.com/)
- [TechRadar](https://www.techradar.com/uk)
- [Todoist](https://todoist.com/)
- Appointedd
- Calendly
- Todoist
See above 
=> fix: Create software-services and add words to companies

dictionaries/software-terms/cspell-ext.json, dictionaries/software-terms/cspell-tools.config.yaml, dictionaries/software-terms/cspell.json, dictionaries/software-terms/dict/webServices.txt, dictionaries/software-terms/package.json, dictionaries/software-terms/source-files-networking.txt, dictionaries/software-terms/source-files.txt, dictionaries/software-terms/src/README.md, dictionaries/software-terms/src/source-files-networking.txt, dictionaries/software-terms/src/source-files-software.txt
Dictionary: Add _web-services_ dictionary to the software terms package.
=> feat: Add Web Services Dictionary

dictionaries/fullstack/README.md
Dictionary: _fullstack_
Improve the readme.
=> fix: Improve the text in README

dictionaries/es_ES/cspell-ext.json, dictionaries/sk_SK/cspell-ext.json, dictionaries/sk_SK/cspell.json, dictionaries/sk_SK/samples/Bratislava.md, dictionaries/sk_SK/samples/cspell.json
Dictionary: `sk-sk` and `es-es`
Update the dictionary information to improve the suggestions.
=> fix: improve suggestions

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: English
Add: walk-through and walk-throughs
=> fix: Add walk-through

dictionaries/software-terms/src/software-terms.txt
Add `walkthrough` and `walkthroughs`.
[Google Ngram Viewer: walkthough and walkthroughs vs cellphone ](https://books.google.com/ngrams/graph?content=walkthroughs%2Cwalkthrough%2Conboarding%2Ccellphone&year_start=2000&year_end=2019&corpus=en-2019&smoothing=3)
=> fix: Add `walkthrough` and `walkthroughs`

dictionaries/powershell/src/powershell.txt
=> fix: Add endregion to powershell

dictionaries/powershell/src/powershell.txt
=> fix: Add notmatch to powershell

dictionaries/powershell/src/powershell.txt
=> fix: Add hashtable to powershell

dictionaries/powershell/src/powershell.txt
=> fix: Add notin to powershell

dictionaries/fr_FR/cspell-ext.json, dictionaries/fr_FR_90/cspell-ext.json
fixes #1982
This used to work, but had been removed for some reason. I'm adding the repMap back.
=> fix: French `'` issue

dictionaries/al/cspell-ext.json, dictionaries/al/cspell.json, dictionaries/al/samples/MyPage.al, dictionaries/al/samples/boolean.al
Dictionary: _`al`_
Add some AL samples.
=> fix: Add some AL samples

dictionaries/latex/dict/latex.txt, dictionaries/php/dict/php.txt, dictionaries/ruby/dict/ruby.txt, package.json, yarn.lock
This update changes legacy splitter slightly.
=> fix: Update cspell-tools

dictionaries/latex/cspell-tools.config.yaml, dictionaries/latex/package.json
Dictionary: _latex_
Use config file to specify build.
=> chore: Use cspell-tools build

dictionaries/ruby/cspell-tools.config.yaml, dictionaries/ruby/dict/ruby.txt, dictionaries/ruby/package.json, dictionaries/ruby/src/allowed-terms.txt
=> fix: (ruby) Allow only English word splits

dictionaries/powershell/src/powershell.txt
=> fix: Add Clixml to PowerShell

dictionaries/fullstack/dict/fullstack.txt
Dictionary: fullstack.txt
Add `nestjs` (I could also add it localy, but may help others)
- ![image](https://user-images.githubusercontent.com/44493964/226575933-be6a3adc-9dba-4c2c-aaaa-df1014940793.png)
=> fix: add `nestjs`

dictionaries/fullstack/src/fullstack.txt
Dictionary: fullstack.txt
Add `nestjs` (I could also add it localy, but may help others)
- ![image](https://user-images.githubusercontent.com/44493964/226575933-be6a3adc-9dba-4c2c-aaaa-df1014940793.png)
=> fix: Update fullstack.txt

dictionaries/en_shared/src/shared-additional-words.txt
PR for adding "minimalistic" to the `en_shared` dictionary.
Add new word "minimalistic".
[Wikipedia](https://en.wiktionary.org/wiki/minimalistic)
[Cambridge English Dictionary](https://dictionary.cambridge.org/us/dictionary/english/minimalistic)
[Dictionary.com](https://www.dictionary.com/browse/minimalistic)
=> fix: add `minimalistic` to en_shared

dictionaries/fonts/fonts.txt
- add Iosevka to font dictionary
Dictionary: fonts
Add Iosevka to list of fonts
- https://github.com/be5invis/Iosevka
=> fix: Add Iosevka to list of fonts

dictionaries/software-terms/src/software-terms.txt
add "MLP" "perceptron"  "ResNet" 
https://en.wikipedia.org/wiki/Residual_neural_network
Update software-terms.txt
=> fix: Update software-terms.txt

dictionaries/python/cspell-tools.config.yaml, dictionaries/python/package.json, dictionaries/python/src/common_packages.txt, dictionaries/python/src/data_science.txt
=> chore: Add some new Python source files

dictionaries/software-terms/src/software-terms.txt
add "torchrun autograd megatron " etc.
add "torchrun autograd megatron "
torchrun
https://pytorch.org/docs/stable/elastic/run.html
autograd 
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html
etc.
=> fix: Add AI terms to software terms

dictionaries/python/src/data_science.txt
add some words with data_science.txt
=> fix: Update data_science.txt

dictionaries/en_US/src/additional_words.txt
=> fix: Add `discretization` to en_us

dictionaries/companies/src/companies.txt
=> fix: Update companies.txt, add Alipay

dictionaries/companies/src/companies.txt, dictionaries/python/src/data_science.txt, dictionaries/software-terms/src/network-protocols.txt, dictionaries/software-terms/src/software-terms.txt
fix: add words to data_science network-protocols software-teams
add some words 
detail info 
modified:   dictionaries/python/src/data_science.txt
modified:   dictionaries/software-terms/src/network-protocols.txt
modified:   dictionaries/software-terms/src/software-terms.txt
=> fix: add words to data_science network-protocols software-teams

scripts/.eslintrc.json, scripts/sort-source.mjs
The method that sorted source files didn't work correctly with files with comments.
=> chore: fix the source sorter

dictionaries/companies/src/companies.txt, dictionaries/golang/src/go.txt
add GOPATH to go.txt 
add Tencent to companies.txt
add GOPATH to go.txt 
add Tencent to companies.txt
=> fix: add GOPATH to go.txt add Tencent to companies.txt

dictionaries/software-terms/src/network-protocols.txt
Dictionary: network-protocols.txt
add word to network-protocols.txt
NLRI           RFC 5549 
Multiprotocol  RFC 4760
Subcodes       RFC 6608 
EBGP           RFC 8212
RPKI           RFC 6480
veth           (virtual interfaces) from linux kernel 
=> fix: add word to network-protocols.txt

dictionaries/data-science/src/data-science-terms.txt
Dictionary: data-science-terms.txt
add some words to data-science-terms.txt
detail info
modified:   dictionaries/data-science/src/data-science-terms.txt
Hypercuboids https://arxiv.org/pdf/2011.05742.pdf
Autoencoder  https://link.springer.com/chapter/10.1007/978-981-15-6325-6_5
Polyak       https://arxiv.org/pdf/2002.04664.pdf
UniEval      https://arxiv.org/abs/2210.07197
VLMO         https://arxiv.org/abs/2111.02358
DSVAE        https://arxiv.org/abs/2304.03323
LATM         LLMs As Tool Makers
DALL-E       https://openai.com/research/dall-e
DALLE
=> fix: add some words to data-science-terms.txt

dictionaries/data-science/src/data-science-terms.txt, dictionaries/software-terms/src/software-terms.txt
Dictionary: software-terms  data-science-terms
add DeepScale ICLR to software-terms 
add interpretability explainability to data-science-terms
DeepScale         https://en.wikipedia.org/wiki/DeepScale
ICLR              https://iclr.cc/Conferences/2023
"Interpretability" and "explainability" are both terms related to artificial intelligence and machine learning, and they both concern the explainability of models.
"Interpretability" usually refers to the explainability of machine learning models, meaning that the predicted results of the models can be interpreted or understood. This often involves explaining the decision-making process of the model so that users can understand why the model made a specific prediction. In the field of deep learning, where models are complex and black-box, …
=> fix: add DeepScale ICLR to software-terms add interpretability explainability to data-science-terms

dictionaries/en_US/src/additional_words.txt
Dictionary: _additional_words.txt_
_add 'rebrand' and 'rebranding' to additional_words.txt_
- https://en.wikipedia.org/wiki/Rebranding
- https://www.oxfordlearnersdictionaries.com/definition/american_english/rebrand#rebrand__11
=> fix: add 'rebrand' and 'rebranding' to en-US

dictionaries/data-science/src/data-science-terms.txt
…-terms
add feedforward hyperscale superpod deepfusion Conv1d to data-science-terms
feedforward       https://en.wikipedia.org/wiki/Feedforward_neural_network
hyperscale        https://en.wikipedia.org/wiki/Hyperscale_computing
superpod          https://www.nvidia.com/en-us/data-center/dgx-superpod/
deepfusion	  https://arxiv.org/abs/2203.08195
Conv1d            https://arxiv.org/abs/2104.01560
=> fix: add feedforward hyperscale superpod deepfusion Conv1d to data-science terms

dictionaries/powershell/dict/powershell.txt
=> fix: Add `notcontains` to PowerShell dictionary

dictionaries/companies/src/companies.txt, dictionaries/data-science/src/data-science-terms.txt
add xlarge microbatch leaderboard to data-science-terms.txt
Dictionary: companies.txt  data-science-terms.txt
add ICCC ISEA to companies.txt
add xlarge microbatch leaderboard to data-science-terms.txt
| ICCC         | http://www.iccc.org/                              |
|--------------|---------------------------------------------------|
| ISEA         | https://www.isea.org/                             |
| xlarge       | https://instances.vantage.sh/aws/ec2/p4d.24xlarge |
| microbatch   | https://arxiv.org/abs/1903.10520                  |
| leaderboard  | https://arxiv.org/abs/2104.06387                  |
=> fix: add ICCC ISEA to companies.txt add xlarge microbatch leaderboard to data-science-terms.txt

dictionaries/npm/cspell-ext.json
=> fix: Update description of the `npm` dictionary

dictionaries/data-science/src/data-science-terms.txt
fix: add Widenet SISD MISD etc. to data-science-terms
modified:   dictionaries/data-science/src/data-science-terms.txt
| Widenet       |                               | https://arxiv.org/abs/2107.11817     |
|---------------|-------------------------------|--------------------------------------|
| SISD          | Single Instance Single Device | https://arxiv.org/pdf/2111.14247.pdf |
| MISD          | Multi Instance Single Device  | https://arxiv.org/pdf/2111.14247.pdf |
| SIMD          | Single Instance Multi Device  | https://arxiv.org/pdf/2111.14247.pdf |
| MIMD          | Multi Instance Multi Devices  | https://arxiv.org/pdf/2111.14247.pdf |
| FSDP          | Fully Sharded Data Parallel   | https://arxiv.org/abs/2304.11277     |
| convolutional | …
=> fix: add Widenet SISD MISD etc. to data-science-terms

dictionaries/npm/cspell-ext.json
=> fix: Update npm description in extension.

dictionaries/data-science/src/data-science-terms.txt
Dictionary: data-science-terms.txt
add hyperparameters abstractive etc. to data-science-terms.txt
| Word    | Reference |
|-----------------|----------------------------------------|
| engagingness    | https://arxiv.org/pdf/2105.00071v1.pdf |
| groundedness    | https://arxiv.org/pdf/2105.00071v1.pdf |
| hyperparameters | https://arxiv.org/pdf/2105.00071v1.pdf |
| abstractive     | https://arxiv.org/pdf/2105.00071v1.pdf |
=> fix : add hyperparameters abstractive etc. to data-science-terms.txt

dictionaries/companies/src/companies.txt
Dictionary: companies.txt
add USENIX OSDI SIGKDD to companies.txt
https://www.usenix.org/conference/osdi23 
https://kdd.org/kdd2023/
=> fix: add USENIX OSDI SIGKDD to companies.txt

dictionaries/data-science/src/data-science-terms.txt
fix: add Dataloaders convolutionally MoElayer WAIC to data-science-terms
Dataloaders      https://arxiv.org/abs/2209.13705
convolutionally  https://arxiv.org/abs/1701.06538
MoElayer         Mixture-of-Experts layer  https://arxiv.org/abs/1701.06538
WAIC             World Artificial Intelligence Conference
=> fix: add Dataloaders convolutionally MoElayer WAIC to data-science-terms

dictionaries/data-science/src/data-science-terms.txt
fix: add eigen to data-science-terms
eigen     https://arxiv.org/pdf/1903.11240.pdf
=> fix: add eigen to data-science-terms

dictionaries/el/source-files.txt, dictionaries/el/src/additional_words.txt
Dictionary: `el`
- `feat!:` - for breaking changes, like file format changes.
=> fix: Support adding Greek words

dictionaries/sk_SK/cspell-tools.config.yaml, dictionaries/sk_SK/src/additional_words.txt
Dictionary: sk-sk
Support adding words to `src/additional_words.txt`
- `feat!:` - for breaking changes, like file format changes.
=> fix: support additional works

dictionaries/python/src/python/python.txt
Dictionary: python.txt
add qualname to python
__qualname__   https://peps.python.org/pep-3155/#proposal
- `feat!:` - for breaking changes, like file format changes.
=> fix: add qualname to python

dictionaries/python/src/common_packages.txt
Dictionary: common_packages
fix: add pathlib oneflow to common_packages
pathlib          https://pypi.org/project/pathlib
oneflow          https://pypi.org/project/oneflow/
=> fix: add pathlib oneflow to common_packages

dictionaries/python/src/common_packages.txt
Dictionary: common_packages
fix: add Bokeh Chainer etc. to common_packages
| Bokeh         | https://pypi.org/project/bokeh/          |
|---------------|------------------------------------------|
| Chainer       | https://pypi.org/project/chainer/        |
| Gensim        | https://pypi.org/project/gensim/         |
| Keras         | https://pypi.org/project/keras/          |
| Matplotlib    | https://pypi.org/project/matplotlib/     |
| Pipenv        | https://pypi.org/project/pipenv/         |
| Plotly        | https://pypi.org/project/plotly/         |
| Pydot         | https://pypi.org/project/pydot/          |
| Scikit-learn  | https://pypi.org/project/scikit-learn/   |
| Scrapy        | https://pypi.org/project/Scrapy/         |
| Theano        | https://pypi.org/project/Theano/ …
=> fix: add Bokeh Chainer etc. to common_packages

package.json
=> chore: downgrade pnpm

dictionaries/companies/src/companies.txt, dictionaries/npm/src/npm.txt, dictionaries/software-terms/src/software-services.txt
Dictionary: 
- NPM
- Companies 
- Software-Services
- Add  [lyricssearchermusixmatch](https://www.npmjs.com/package/lyrics-searcher-musixmatch?activeTab=readme) to npm
- Add [musixmatch](https://www.musixmatch.com/) to companies and services
See above
=> fix: Add words to various dicts

dictionaries/fonts/src/fonts.txt
Dictionary: fonts
Added missing [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) to fonts.
- https://github.com/ryanoasis/nerd-fonts
=> fix: Add missing Nerd-Fonts

dictionaries/data-science/src/data-science-terms.txt
add adaptative anonymization etc. to data-science-terms
| Term        | Reference |
|-------------------|----------------------------------|
| adaptative        | https://arxiv.org/abs/2307.09936 |
| anonymization     | https://arxiv.org/abs/2211.09454 |
| autoregression    | https://arxiv.org/abs/2203.15170 |
| CCPA              | https://arxiv.org/abs/2109.13816 |
| chatbots          | https://arxiv.org/abs/2201.06657 |
- …
=> fix: add adaptative anonymization etc. to data-science-terms

dictionaries/data-science/src/data-science-terms.txt
fix: add Ecolinguistics etc. to data-science-terms
| Term    | Reference |
|-------------------|----------------------------------------------|
| Ecolinguistics    | https://en.wikipedia.org/wiki/Ecolinguistics |
| inclusivity       | https://arxiv.org/abs/2301.01590             |
| interpretability  | https://arxiv.org/abs/2103.10689             |
| Metaverse         | https://en.wikipedia.org/wiki/Metaverse      |
- `chore:` …
=> fix: add Ecolinguistics etc. to data-science-terms

dictionaries/companies/src/companies.txt
Dictionary: companies.txt
fix: add Deloitte Dezzai Lumitics Midjourney to companies.txt
| Term     | Reference          |
|--------------|-----------------------------------------------|
| Deloitte     | https://www2.deloitte.com/us/en.html          |
| Dezzai       | https://dezzai.com/en/                        |
| Lumitics     | https://lumitics.com/                         |
| Midjourney   | https://www.midjourney.com/                   |
- `chore:` - …
=> fix: add Deloitte Dezzai Lumitics Midjourney to companies.txt

dictionaries/data-science/src/data-science-terms.txt
fix: add Neuro-Symbolic etc. to data-science-terms
| Term     | Reference      |
|--------------------|--------------------------------------|
| Neuro-Symbolic     | https://arxiv.org/abs/2208.00374     |
| Overfitting        | https://arxiv.org/abs/2209.06053     |
| SOTA               | https://arxiv.org/abs/2204.08442     |
| Synergizing        | https://arxiv.org/abs/2210.03629     |
| transformative     | https://arxiv.org/abs/1811.03392     |
| operationalization | https://arxiv.org/abs/2302.00033     |
- `feat:` - for a significant change like adding a whole new set of words to a …
=> fix: add Neuro-Symbolic etc. to data-science-terms

dictionaries/companies/src/companies.txt
fix: add RIMAS to companies
| RIMAS | Risk and Insurance Management Association of Singapore | https://www.rimas.org.sg/ |
|-------|--------------------------------------------------------|---------------------------|
=> fix: add RIMAS to companies

dictionaries/python/src/common_packages.txt
Dictionary: common_packages
fix: add pybindll docutils to common_packages
| Term | Reference |
|----------|------------------------------------|
| pybind11 | https://pypi.org/project/pybind11/ |
| docutils | https://pypi.org/project/docutils/ |
=> fix: add pybindll docutils to common_packages

dictionaries/data-science/src/data-science-terms.txt
fix: add interpretability Synergizing to data-science-terms
| Term | Reference |
|------------------|----------------------------------|
| interpretability | https://arxiv.org/abs/2210.03629 |
| Synergizing      | https://arxiv.org/abs/2210.03629 |
=> fix: add interpretability Synergizing to data-science-terms

dictionaries/software-terms/dict/softwareTerms.txt
Add "Backoff" to software terms dictionary
Used in the context of [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)
=> fix: Add "Backoff" to the software terms dict

dictionaries/medicalterms/package.json
Dictionary: Medical Terms
Upgrade as part of #705 
NA
=> feat!: Upgrade Medical Terms Dictionary

dictionaries/medicalterms/checksum.txt, dictionaries/medicalterms/cspell-tools.config.yaml, dictionaries/medicalterms/package.json, dictionaries/medicalterms/src/additional_words.txt, scripts/test-package-files.mjs
Dictionary: `dict-medicalterms`
Be able to detect changes to the medical terms source.
=> chore: Support conditional build for medical terms

dictionaries/cryptocurrencies/LICENSE, dictionaries/cryptocurrencies/package.json
=> fix: Adjust crypto license

dictionaries/companies/src/companies.txt
add xiaomi to companies
[Xiaomi](https://www.mi.com/global/about/)
=> fix: add xiaomi to companies

dictionaries/en_GB-MIT/checksum.txt
=> chore: Update checksum file

dictionaries/eu/package.json, dictionaries/eu/src/basque_hunspell/README.md, package.json, pnpm-lock.yaml
Dictionary: Basque
Remove dependency upon private repository.
It seems that the Basque dictionary was removed.
@jmigartua, did you move the dictionary?
=> chore: fix broken dependency

dictionaries/companies/src/companies.txt
Add OpenAI
https://en.wikipedia.org/wiki/OpenAI
=> fix: Add OpenAI to companies

dictionaries/css/src/css.txt
Add `easings` to css dictionary
https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function
=> fix: add easings to css dictionary

dictionaries/html/src/html.txt
https://en.wikipedia.org/wiki/WebP
=> fix: add webp to html dictionary

dictionaries/npm/src/npm.txt
Add `trpc` to software terms
https://en.wikipedia.org/wiki/TRPC
=> fix: add trpc to software terms

dictionaries/shell/src/shell-zsh-words.txt
add zsh shell words:
- bindkey
https://zsh.sourceforge.io/Intro/intro_11.html
=> fix: add bindkey zsh shell words

dictionaries/software-terms/src/software-terms.txt
https://tree-sitter.github.io/tree-sitter/
=> fix: add treesitter to software terms

dictionaries/css/src/css.txt
- tundora: (hex: #5A5958)
- bluehaze: (hex: #B3B3CC)
- offwhite: (hex: #FAF9F6)
=> fix: add bluehaze and tundora to css dictionary

dictionaries/npm/src/npm.txt
https://www.npmjs.com/package/superjson
=> fix: add superjson to npm

dictionaries/npm/src/npm.txt
https://www.npmjs.com/package/heroicons
=> fix: add heroicons to npm

dictionaries/software-terms/src/software-terms.txt
- blankline
- unmap
- unstage (git)
- unstaged (git)
=> fix: add software terms

dictionaries/npm/src/npm.txt
- tailwind https://tailwindcss.com/
- nextjs https://nextjs.org/
- nextauth https://next-auth.js.org/
=> fix: add tailwind and tailwindcss to npm

dictionaries/software-terms/src/software-terms.txt, dictionaries/software-terms/src/software-tools.txt
- printscreen
- ctag/ctags https://en.wikipedia.org/wiki/Ctags
- prettier/prettierd https://github.com/fsouza/prettierd
- automake https://en.wikipedia.org/wiki/Automake
- dotfiles (configuration)
=> fix: update software terms and tools

dictionaries/python/src/python/python.txt
https://github.com/pyenv/pyenv
=> fix: add pyenv to python

dictionaries/companies/src/companies.txt
https://en.wikipedia.org/wiki/OpenDNS
=> fix: add OpenDNS to companies

dictionaries/npm/src/npm.txt
part of pnpm (https://pnpm.io)
=> fix: add pnpx

dictionaries/npm/src/npm.txt
- typegen https://stately.ai/docs/xstate/typescript/typegen/
- docgen https://react-docgen.dev/
- hookform https://react-hook-form.com/
- lucide https://lucide.dev/
=> fix: update npm

dictionaries/software-terms/src/software-terms.txt, dictionaries/software-terms/src/software-tools.txt
- commandline
- keychain
- cypher https://en.wikipedia.org/wiki/Cypher_(query_language)
- ripgrep https://github.com/BurntSushi/ripgrep
=> fix: update software terms

dictionaries/npm/src/npm.txt
https://github.com/TanStack/query
=> fix: add tanstack to npm

dictionaries/he/README.md
=> doc: Update Hebrew README

dictionaries/software-terms/src/software-terms.txt
- unmocked (not mocked)
- unoptimized (not optimized)
=> fix: add unmocked and unoptimized to software terms

dictionaries/ruby/src/ruby.txt
- haml https://en.wikipedia.org/wiki/Haml
- byebug https://github.com/deivid-rodriguez/byebug
- cloneable https://apidock.com/ruby/v2_6_3/Object/clone
- lambda https://ruby-doc.org/core-2.7.1/Proc.html#method-i-lambda-3F
=> fix: update ruby dictionary

dictionaries/companies/src/companies.txt
- Cloudinary https://cloudinary.com/
- Egnyte https://www.egnyte.com/
=> fix: add Cloudinary and Egnyte to companies

dictionaries/lua/src/lua.txt
https://keplerproject.github.io/luadoc/
=> fix: add luadoc to lua dictionary

dictionaries/kotlin/cspell-ext.json, dictionaries/kotlin/cspell.json, dictionaries/kotlin/package.json, dictionaries/kotlin/samples/CardViewActivity.kt, dictionaries/kotlin/samples/CardViewFragment.kt
Include Java dictionary by default, since Kotlin in Java based.
=> chore: prepare to publish Kotlin

dictionaries/scientific_terms_GB/package.json, dictionaries/scientific_terms_GB/samples/README.md
=> chore: prepare publish

.yarnrc, package.json
=> chore: clean up yarn cruft

generator-cspell-dicts/generators/app/index.js, generator-cspell-dicts/package.json, pnpm-lock.yaml
- Update yeoman-generator to use modules.
- use `yeoman-generator` `^6.0.1`
=> chore: Update dictionary generator

dictionaries/software-terms/src/software-tools.txt
=> fix: add mitmproxy to software tools

dictionaries/software-terms/src/software-tools.txt
- speedtest: [https://www.speedtest.net/](https://www.speedtest.net/)
- httpie: [https://httpie.io](https://httpie.io/)
- wkhtmltopdf: [https://wkhtmltopdf.org/](https://wkhtmltopdf.org/)
=> fix(software-tools): add httpie, wkhtmltopdf, speedtest

dictionaries/makefile/cspell-ext.json, dictionaries/makefile/cspell.json, dictionaries/makefile/package.json, dictionaries/makefile/samples/makefile, generator-cspell-dicts/generators/app/templates/package.json
Dictionary: _makefiles_
Detect makefiles and set the `languageId` (file type).
=> fix: Set the `languageId` for `makefiles`

dictionaries/companies/dict/companies.txt
fix: add CSAIL to companies
fix: add CSAIL to companies
| CSAIL | Computer Science & Artificial Intelligence Laboratory | https://www.csail.mit.edu/ | 
=> fix: add CSAIL to companies

.github/pull_request_template.md, generator-cspell-dicts/package.json, pnpm-lock.yaml
=> chore: Update yeoman-generator to v7

.github/pull_request_template.md, generator-cspell-dicts/package.json, pnpm-lock.yaml
=> chore: Update yosay

dictionaries/python/src/python/python.txt
Add "venvs" to the python dict
[Python documentation](https://docs.python.org/3/library/venv.html#how-venvs-work) of how venvs work.
=> fix: Add "venvs" to the python dict

dictionaries/da_DK/package.json, dictionaries/de_AT/package.json, dictionaries/de_CH/package.json, dictionaries/de_DE/package.json, dictionaries/el/package.json, dictionaries/es_ES/package.json, dictionaries/et-EE/package.json, dictionaries/it_IT/package.json, dictionaries/lv/package.json, dictionaries/nl_NL/package.json, dictionaries/pt_BR/package.json, dictionaries/ro_RO/package.json, dictionaries/ru_RU/package.json, dictionaries/sv/package.json, dictionaries/uk_UA/package.json, pnpm-lock.yaml
Dictionary: All dictionaries depending upon https://github.com/wooorm/dictionaries
Wooorm has released the dictionaries with a major version bump: https://github.com/wooorm/dictionaries
=> feat: Update dictionary sources

.github/workflows/test.yml, cspell-dict-file-checker/package.json, package.json, pnpm-lock.yaml
=> chore: Upgrade CSpell to v8

dictionaries/software-terms/src/software-tools.txt
https://ss64.com/osx/pbcopy.html
https://ss64.com/osx/pbpaste.html
=> fix: add pbcopy and pbpaste to software terms

dictionaries/companies/src/companies.txt, dictionaries/en_shared/src/shared-additional-words.txt, dictionaries/filetypes/filetypes.txt, dictionaries/npm/src/npm.txt, dictionaries/software-terms/src/software-terms.txt, dictionaries/software-terms/src/software-tools.txt
Adding various terms.
fixes: #2720
=> fix: add various terms

dictionaries/software-terms/src/software-terms.txt
fix: add pseudocode to software-terms.txt
https://simple.wikipedia.org/wiki/Pseudocode
=> fix: add Pseudocode

dictionaries/lua/src/lua.txt
https://github.com/JohnnyMorganz/StyLua
=> Add stylua to lua dictionary

dictionaries/es_ES/src/additional_words.txt
Dictionary: es_ES
Add some missing terms to Spanish dictionary
- [desactualizada](https://dle.rae.es/desactualizado)
- [desactualizado](https://dle.rae.es/desactualizado)
- [expendio](https://dle.rae.es/expendio)
=> fix: Add some missing terms to Spanish dictionary

dictionaries/aws/src/aws.txt
Dictionary: aws
Add "buildspec" term
- https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
=> fix: [aws] Add "buildspec" term

dictionaries/software-terms/src/computing-acronyms.txt, dictionaries/software-terms/src/software-terms.txt
Add some missing IT & software related terms
- [Cyclomatic](https://en.wikipedia.org/wiki/Cyclomatic_complexity);
- [DBAL / DAL](https://en.wikipedia.org/wiki/Database_abstraction_layer);
- [JSON](https://en.wikipedia.org/wiki/JSON);
- [JSONLD](https://en.wikipedia.org/wiki/JSON-LD);
- [JWT](https://en.wikipedia.org/wiki/JSON_Web_Token);
- Autoconfigure:
- https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/using-boot-auto-configuration.html#using-boot-disabling-specific-auto-configuration
- https://symfony.com/doc/current/service_container.html#the-autoconfigure-option
- Autowire / Autowired / Autowiring:
- https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html
- …
=> fix: Add some missing IT & software related terms

dictionaries/companies/src/companies.txt
Add some company names
- [Bimbo Bakeries USA](https://www.bimbobakeriesusa.com/);
- [Nubity Inc.](https://nubity.com/);
- [Slevomat](https://www.slevomat.cz/).
=> fix: [companies] Add some company names

dictionaries/php/src/php.txt
Dictionary: php
Add some vendor and package names
- [friendsofphp](https://github.com/FriendsOfPHP);
- [hautelook](https://github.com/theofidry/AliceBundle/blob/7b8cf62973853ec406ecb27f3b90b91a1b525a05/composer.json#L2);
- [httplug](https://httplug.io/);
- [nelmio](https://github.com/nelmio);
- [phpcs](https://github.com/squizlabs/PHP_CodeSniffer/blob/7763e2e1f773cb0615ed8afa133189fc804f583d/phpcs.xml.dist#L2).
=> fix: [php] Add some vendor and package names

dictionaries/python/src/common_packages.txt
Add "djlint" term
- https://www.djlint.com/;
- https://pypi.org/project/djlint/.
=> fix: [python] Add "djlint" term

dictionaries/software-terms/src/software-terms.txt
https://en.wiktionary.org/wiki/evaluatable
=> fix: add `evaluatable` to software terms

dictionaries/cryptocurrencies/package.json
Dictionary: _cryptocurencies_
- The legacy dictionary was missing from the package.
=> fix: Crypto make sure dict files are packaged.

dictionaries/en-common-misspellings/LICENSE, dictionaries/en-common-misspellings/README.md, dictionaries/en-common-misspellings/cspell.json, dictionaries/en-common-misspellings/package.json
Dictionary: en-common-misspellings
Update license for en-common-misspellings Dictionary
https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/en-common-misspellings 
[Wikipedia:Lists of common misspellings/For machines - Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines)
[Wikipedia:Lists of common misspellings - Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings)
=> feat!: Update en-common-misspellings license to CC BY-SA 4.0

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: Shared English
Adds five words to shared English dictionary
https://www.merriam-webster.com/dictionary/haikus
https://www.merriam-webster.com/dictionary/disambiguates
https://www.merriam-webster.com/dictionary/sorcerous
MW did not list the other two
=> fix: Add several English terms [fix #2823]

dictionaries/cpp/cspell-tools.config.yaml, dictionaries/cpp/src/additional-terms.txt
Dictionary: _CPP_
- add `src/additional-terms.txt` file to support easily adding new terms.
=> fix: Support adding additional terms to the CPP dict

dictionaries/software-terms/src/software-terms.txt
- https://en.wikipedia.org/wiki/Speaker_diarisation
=> fix: Add diarization

dictionaries/companies/src/companies.txt
Added the name of the company I'm working for.
- https://www.durr.com
- https://www.homag.com/
=> fix: add DÜRR and HOMAG to companies

dictionaries/companies/src/companies.txt
Add AdGuard to companies
https://adguard.com/en/welcome.html
=> fix: Add AdGuard to companies

cspell.config.yaml, dictionaries/k8s/cspell.json, dictionaries/makefile/cspell.json, dictionaries/sl_SI/cspell.json, dictionaries/vim/cspell.json
=> chore: Do not spell check devDependencies

dictionaries/hu_HU/cspell-ext.json, dictionaries/hu_HU/cspell.json, dictionaries/hu_HU/package.json, dictionaries/hu_HU/samples/seattle.md
Dictionary: _hu-HU_
Reduce the Hungarian package size by using .gz
=> fix: bundle .trie.gz instead of .trie

dictionaries/companies/src/companies.txt, dictionaries/npm/src/npm.txt
Dictionary: npm and companies
Add `fastify` and `pino` to `npm` dictionary, and `Yassir` to companies
=> fix: add Fastify and pino to libraries; Yassir to companies

dictionaries/en_US/src/en_US.txt
Dictionary: _en_US_
fixes: #2940
=> fix: remove misspelling from English word list

dictionaries/fi_FI/package.json
=> chore: prepare to publish Finish

dictionaries/software-terms/src/software-terms.txt
Adding voxel and its plural form, voxels.
- [Voxel - Wikipedia](https://en.wikipedia.org/wiki/Voxel)
=> fix(software-terms): voxel

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: English
Add revalidates to shared-additional-words.txt
Fixes #2958 
=> fix: Add revalidates to shared-additional-words.txt

dictionaries/cpp/src/cpp.txt
Dictionary: cpp
fixes [#2968](https://github.com/streetsidesoftware/cspell-dicts/issues/2968)
=> fix: Fix spelling of compatiblity in CPP word list (to compatibility)

dictionaries/software-terms/src/software-tools.txt
software-tools.txt
add Jetbrains and IntelliJ to software-tools.txt
https://www.jetbrains.com/
https://www.jetbrains.com/idea/
=> [fix] add Jetbrains and IntelliJ to software-tools.txt

dictionaries/la/LICENSE, dictionaries/la/README.md, dictionaries/la/package.json
=> fix: Adjust license and prepare to publish

pnpm-lock.yaml, scripts/package.json, scripts/sort-source.mjs
=> chore: Tools - Update dependency

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: English All
Add word: `mitigations`
- [Mitigations Definition & Meaning - Merriam-Webster](https://www.merriam-webster.com/dictionary/mitigations)
=> fix: Add `mitigations` to English shared-additional-words.txt

dictionaries/ru_RU/README.md
Fix Readme file.
Fix 404 link to additional words.
N/A.
=> docs: fix link to additional words

dictionaries/julia/cspell-ext.json, dictionaries/julia/samples/cspell.json
Dictionary: _julia_
- Use overrides to associate `.jl` files with Julia file type.
=> fix: Associate `.jl` files with julia language

dictionaries/vim/src/vim.txt
https://neovim.io/doc/user/builtin.html#setreg()
=> fix(vim-dictionary): add setreg

dictionaries/es_ES/src/additional_words.txt
Dictionary: spanish
Added new valid words: comparabilidad, pizarrón, videollamada, relevamiento
Checked against authorative RAE Real Academia Española
comparabilidad: https://dle.rae.es/comparabilidad
pizarrón: https://dle.rae.es/pizarrón
videollamada: https://dle.rae.es/videollamada
relevamiento: https://dle.rae.es/relevamiento
=> fix: Add new valid words: comparabilidad, pizarrón, videollamada, relevamiento

dictionaries/elisp/cspell-ext.json, dictionaries/elisp/cspell.json, dictionaries/elisp/package.json, dictionaries/elisp/samples/cspell.json, dictionaries/elisp/samples/examples.el
=> chore (elisp): add example and prepare to publish

dictionaries/vim/src/vim.txt
https://neovim.io/doc/user/quickfix.html
- qflist
- getqflist
- setqflist
=> fix(vim-dictionary): add qflist

dictionaries/typescript/src/typescript.txt
Dictionary: typescript.txt
fix #3071 add dataavailable and ondataavailable to typescript.txt
=> fix: add dataavailable and ondataavailable to typescript.txt

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary:  shared-additional-words.txt
fix #2755 add swiper to shared-additional-words.txt
=> fix: add swiper to shared-additional-words.txt

dictionaries/software-terms/src/software-terms.txt, dictionaries/typescript/src/typescript.txt
Dictionary: _typescript_ and _software-terms_
`IIFE` in an acronym for Immediately Invoked Function Expression.
- https://en.wikipedia.org/wiki/Immediately_invoked_function_expression
=> fix: add `iife` to TypeScript dictionary

dictionaries/golang/src/go.txt
Dictionary: golang
Add "GOGC" to the dict.
https://tip.golang.org/doc/gc-guide
=> fix: add "GOGC" to golang dictionary 

dictionaries/fullstack/src/fullstack.txt
=> fix: update fullstack dict

dictionaries/companies/src/companies.txt
Add more companies to the dict
- Based on https://docs.victoriametrics.com/casestudies/
=> fix: update companies dictionary

dictionaries/en-common-misspellings/dict-en.yaml
Dictionary: en-common-misspellings
Add a couple more options
- N/A
=> fix: update en-common-misspellings dict

dictionaries/fullstack/cspell-ext.json
Dictionary: _fullstack_
TypeScriptReact and JavaScriptReact are full stack language variants.
=> fix: Use fullstack dictionary with `typescriptreact` and `javascriptreact`.

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: en-shared
Add `CEST`, `EET`.
N/A
=> fix: update en-shared dict

dictionaries/aws/src/aws.txt
=> fix: update aws dict

dictionaries/companies/src/companies.txt
Add `MHI Vestas Offshore Wind`
- https://www.linkedin.com/company/mhi-vestas-offshore-wind/
=> fix: update companies dict

dictionaries/google/README.md, dictionaries/google/cspell-ext.json, dictionaries/google/cspell.json, dictionaries/google/package.json
Dictionary: _google_
Prepare to publish the Google Cloud Development Dictionary
=> fix: Prepare to publish Google Dict

dictionaries/google/cspell-ext.json
=> fix: Adjust the google dict description

dictionaries/k8s/src/k8s.txt
Dictionary:k8s
Add `HPA`
- https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
=> fix: update k8s dict

dictionaries/software-terms/src/coding-terms.txt, dictionaries/software-terms/src/computing-acronyms.txt, dictionaries/software-terms/src/software-services.txt, dictionaries/software-terms/src/software-terms.txt, dictionaries/software-terms/src/software-tools.txt
=> fix: update software-terms dict

dictionaries/companies/src/companies.txt, dictionaries/google/src/google.txt
Dictionary: companies & google
Added Missing Names
- [X Verify that the title starts with the correct prefix:
=> fix: Add missing company names and Google terms

dictionaries/en_US/src/acronyms.txt, dictionaries/en_US/src/additional_words.txt, dictionaries/en_US/src/en_US.txt
Dictionary: en-us
Add a few new words
N/A
=> fix: update en-us dict

dictionaries/k8s/src/k8s.txt
Dictionary: k8s
Add VPA
- https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
=> fix: Update k8s dict (add VPA)

dictionaries/companies/src/companies.txt
Add Vultr
- https://www.vultr.com/
=> fix: Update companies dict (add Vultr)

dictionaries/software-terms/cspell-tools.config.yaml, dictionaries/software-terms/src/README.md, dictionaries/software-terms/src/cybersecurity-terms.txt
Extend software-terms dictionary with cybersecurity terms.
I'm not sure if I should have been able to create a branch directly as a collaborator. I was getting `ERROR: Permission to streetsidesoftware/cspell-dicts.git denied to arkid15r` so doing it in a fork-based fashion.
Closes #3235 
=> feat: Extend software-terms dictionary w/ cybersecurity terms

dictionaries/software-terms/src/software-tools.txt
- add [Upstash](https://upstash.com/) to software tools
=> fix(software-tools): add upstash

dictionaries/java/src/java-terms.txt
Dictionary: java
Add new terms.
N/A
=> fix: Update java dictionary

dictionaries/php/src/allowed-terms.txt
Dictionary: php
Add `phpsessid`
N/A
=> fix: Update PHP dictionary

dictionaries/software-terms/src/software-tools.txt
Add 3 terms to software terms:
* SVGO
* PostCSS
* postmarketOS
* 17,000,000+ weekly npm downloads: https://www.npmjs.com/package/svgo
* 20,000+ stars on GitHub: https://github.com/svg/svgo
* Website: https://svgo.dev/
* Wikipedia Page: https://en.wikipedia.org/wiki/PostCSS
* 28,000+ stars on GitHub: https://github.com/svg/svgo
* Website: https://postcss.org/
* Wikipedia Page: https://en.wikipedia.org/wiki/PostmarketOS
* 300+ stars on GitLab and 1,000+ issues/PRs: https://gitlab.com/postmarketOS
* Website: https://postmarketos.org/
- `feat!:` - for breaking changes, like file format or licensing …
=> fix: add to software-terms dictionary

dictionaries/people-names/src/names.txt
Dictionary: people-names
Update terms formatting
N/A
=> fix: Update people-names dict

dictionaries/people-names/src/names.txt
Dictionary: people-names
Add more names.
N/A
=> fix: Update people-names dictionary

package.json, pnpm-lock.yaml
=> chore: Upgrade pnpm

.gitattributes, dictionaries/software-terms/cspell.config.yaml, dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/src/coding-terms.txt
These are hex terms used to help debug memory issues.
- See: https://en.wikipedia.org/wiki/Hexspeak
=> fix: Add more Hex Speak terms

dictionaries/people-names/package.json
Dictionary: _dict-people-names_
Enable publishing to NPM.
fixes #3352 
=> fix: Publish People Names

dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: _softwareTerms_
Adding `cobertura` which was matched in the coverage reporter tool config of one of my projects.
- https://cobertura.github.io/cobertura/
=> fix: Add to softwareTerms dictionary

dictionaries/aws/dict/aws.txt, dictionaries/aws/src/aws.txt
Dictionary: _aws_
Adding words to cover the following matched in my CDK project:
- `apigw`: matched in `method.response.header.x-amz-apigw-id` when configuring API Gateway method response headers.
- `apikeys`: matched in `arn:${partition}:apigateway:${region}::/apikeys` when configuring an API Gateway API key ARN.
- `birthdate`: matched when configuring Cognito user pool standard attributes. 
- `fullname`: matched when configuring Cognito user pool standard attributes.
- `requestid`: matched in `method.response.header.x-amzn-requestid` when configuring API Gateway method response headers.
- `usageplans`: matched in `arn:${partition}:apigateway:${region}::/usageplans/${usagePlanId}/keys` when configuring an API Gateway usage plan ARN.
- …
=> fix: Add to aws dictionary

dictionaries/software-terms/cspell-corrections.yaml, dictionaries/software-terms/cspell-ext.json, dictionaries/software-terms/package.json, dictionaries/software-terms/src/coding-terms.txt, dictionaries/software-terms/src/software-terms.txt
Dictionary: _softwareTerms_
BREAKING: Not all versions of cspell support suggestions. This is a major bump to target newer versions.
=> feat!: Add corrections to software-terms

dictionaries/npm/src/npm.txt
=> fix: add npm packages

dictionaries/npm/src/npm.txt
- Remove accidental spelling of Istanbul NPM package.
=> fix: Update npm.txt

dictionaries/software-terms/src/software-terms.txt
> A softphone is a [software](https://en.wikipedia.org/wiki/Computer_software) program for making [telephone](https://en.wikipedia.org/wiki/Telephone) calls over the [Internet](https://en.wikipedia.org/wiki/Internet) using a general purpose computer rather than dedicated hardware.
https://en.wikipedia.org/wiki/Softphone
=> fix(software-terms): add softphone(s)

dictionaries/k8s/src/k8s.txt
Dictionary: k8s
Add kubebuilder
- https://github.com/kubernetes-sigs/kubebuilder
=> fix: Update k8s dict (add kubebuilder)

dictionaries/npm/src/npm.txt, dictionaries/software-terms/src/coding-terms.txt, dictionaries/software-terms/src/software-terms.txt
- add some common front-end coding terms.
=> fix: Add some software coding terms

dictionaries/fullstack/cspell-tools.config.yaml, dictionaries/fullstack/dict/fullstack.txt, dictionaries/fullstack/src/fullstack.txt, dictionaries/fullstack/src/tools-and-services.txt, dictionaries/rust/dict/rust.txt, dictionaries/rust/src/rust.txt, dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/src/software-terms.txt, dictionaries/typescript/cspell-tools.config.yaml, dictionaries/typescript/dict/typescript.txt, dictionaries/typescript/package.json, dictionaries/typescript/src/ecosystem-terms.txt, dictionaries/typescript/src/typescript.txt
Dictionary: software-terms, TypeScript, Rust, Fullstack
- add a few terms related to fullstack development
=> fix: Add some full stack related terms

dictionaries/en-common-misspellings/dict-en.yaml, dictionaries/software-terms/src/software-terms.txt
Dictionary: English Suggestions and Software Terms
- Add POSIX
- Add suggestion for `doens't->doesn't`
=> fix: add POSIX and fix for `doens't`

dictionaries/sql/cspell-tools.config.yaml, dictionaries/sql/source-files.txt, dictionaries/sql/src/common-terms.txt
Dictionary: _SQL_
- Add some common terms found across many .sql files.
=> fix: Add common terms to SQL

dictionaries/software-terms/cspell.config.yaml, dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/package.json, dictionaries/software-terms/src/README.md, dictionaries/software-terms/src/coding-terms.txt, dictionaries/software-terms/src/software-terms.txt
Help define where to add software related words.
=> fix: Update Software Terms README

dictionaries/software-terms/src/computing-acronyms.txt
Add a few software acronyms.
Related to https://github.com/streetsidesoftware/cspell/issues/6065
=> fix: Update computing-acronyms.txt

dictionaries/css/package.json, dictionaries/css/samples/text-rendering.css
Dictionary: _css_
- Add example CSS file
=> test: Add CSS samples

dictionaries/software-terms/src/coding-terms.txt
add upsert
closes #3476
https://en.wikipedia.org/wiki/Merge_(SQL)
=> fix(coding-terms.txt): add upsert

dictionaries/software-terms/src/software-terms.txt
Add a bunch of terms that were missing when adding cspell to my project.
=> fix: Add computing terms

dictionaries/software-terms/src/coding-terms.txt
=> feat: add terms from #3499

dictionaries/python/cspell-ext.json
=> fix: make sure constraints.txt includes python dict

dictionaries/software-terms/src/coding-terms.txt
Fixes an issue related to npm dict.
=> fix: add a couple of coding-terms

dictionaries/npm/src/npm.txt
=> fix: add @sveltejs/eslint-config to npm

dictionaries/npm/src/npm.txt
=> fix: add `@changeset/cli` to npm

dictionaries/dart/src/dart-common.txt
Dictionary: _dart_
- Add `instancetype` - [instanceType function - type_utils library - Dart API](https://pub.dev/documentation/type_utils/latest/type_utils/instanceType.html)
- Add `cstr`
=> fix: Add `instancetype` and `cstr` to Dart

dictionaries/software-terms/src/software-terms.txt
=> fix: Add `stringifyable` to software-terms.txt

dictionaries/software-terms/src/coding-terms.txt
=> fix: A docblock terms to coding terms.

dictionaries/software-terms/src/software-terms.txt
Add `permutate` to software terms
- https://www.merriam-webster.com/dictionary/permutate
=> fix: Add `permutate` to software terms

dictionaries/ruby/src/ruby.txt
Dictionary: Ruby
Add some terms
See inline comments.
=> fix: Add some Ruby words

pnpm-lock.yaml
=> chore: fix lock file

dictionaries/software-terms/src/coding-terms.txt
=> fix: add devcontainer

dictionaries/rust/src/rust.txt
Dictionary: rust
Add rust toolchain program names
=> fix: add rust toolchain names

dictionaries/terraform/src/terraform.txt
=> fix: add terraform terms

dictionaries/software-terms/src/software-tools.txt
=> fix: linux desktop apps words

dictionaries/software-terms/src/coding-terms.txt
=> fix: add microcontroller programming terms

dictionaries/data-science/src/data-science-models.txt
=> fix: add llm terms

.github/workflows/lint.yml
Lock the action/cache version to prevent breaking changes.
=> chore: Update lint.yml

dictionaries/software-terms/src/software-tools.txt
=> fix: add httpbin to software tools

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: shared-additional-words
Add `haptic` & `haptics` to the shared-additional-words dictionary
- https://github.com/streetsidesoftware/cspell-dicts/issues/3655
=> fix(shared-additional-words): haptic/s

dictionaries/software-terms/src/software-terms.txt
add routable
closes #3656
- https://en.wiktionary.org/wiki/routable
=> fix(software-terms.txt): add routable

dictionaries/software-terms/src/software-terms.txt
Add randomizer to software terms
=> fix: Add randomizer to software terms

dictionaries/cspell/cspell-ext.json, dictionaries/cspell/package.json, pnpm-lock.yaml
Dictionary: cspell bundle
Add AL dictionary to CSpell bundle
=> fix: Add AL dict to cspell bundle

dictionaries/npm/src/npm.txt
=> fix: Add tinyglobby to npm

dictionaries/npm/src/npm.txt
=> fix: Add synckit to npm dictionary

dictionaries/node/checksum.txt, dictionaries/node/cspell-ext.json, dictionaries/node/dict/node.txt, dictionaries/node/src/additional_words.txt, dictionaries/node/src/node.txt, dictionaries/npm/cspell-ext.json, dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: _node_, _npm_, _software-terms_
Add `corepack` to software tools and adjust dictionary settings for node and npm. Make sure they are enabled for React.
=> fix: Add `corepack` to tools

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: all English dictionaries
fixes #3760
=> fix: add leaderboard

dictionaries/software-terms/src/software-tools.txt
=> fix: add sysmon

dictionaries/software-terms/src/software-terms.txt
=> fix: add vala programming language

dictionaries/software-terms/src/software-tools.txt
=> fix: add autodocstring vs code plugin

dictionaries/rust/src/rust.txt
=> fix: add missing rust terms

dictionaries/software-terms/src/cybersecurity-terms.txt
- Add KeyCloak to cybersecurity-terms.txt
=> fix: Add KeyCloak to cybersecurity-terms.txt

.github/actions/quick-setup/action.yaml, README.md
- Use Corepack to setup `pnpm`.
=> chore: Use corepack

dictionaries/software-terms/src/software-terms.txt
- Add `easing` to software terms
https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function
=> fix: Add `easing` to software terms

dictionaries/software-terms/src/software-tools.txt
Dictionary: software-tools
Add: `cmake`, `qmake`, ...
=> fix: Add various make tools

dictionaries/en_shared/src/shared-additional-words.txt
Closes #3839
Adds savviness as a word.
- https://scrabble.merriam.com/finder/savviness
=> fix: add savviness

dictionaries/software-terms/src/coding-terms.txt
Closes https://github.com/streetsidesoftware/cspell-dicts/issues/3844
Dictionary: coding-terms
Add some common metasyntactic variables.
https://en.wikipedia.org/wiki/Metasyntactic_variable
http://hackersdictionary.com/html/entry/metasyntactic-variable.html
=> fix: Add metasyntactic variables to coding-terms

dictionaries/python/dict/python.txt, dictionaries/python/src/common_packages.txt
Added some Python package names
- pypi.org
=> fix: Added some Python package names

dictionaries/npm/src/npm.txt, dictionaries/software-terms/src/software-services.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: _npm_, _software-services_, _software-tools_
Adds an assortment of words that known to web development:
* `npm`:
* `arethetypeswrong`
* `astro`
* `astrojs`
* `cookiecutter`
* `degit`
* `tseslint`
* `software-services`:
* `allcontributors`
* `Codespace`
* `Codespaces`
* `software-tools`:
* `tsconfig`
* `TSConfigs`
* `allcontributors`:  https://www.npmjs.com/package/all-contributors -> it's the name of the website and the common GitHub bot
* `arethetypeswrong`: https://www.npmjs.com/package/@arethetypeswrong/cli
* `astro`: https://www.npmjs.com/package/astro
* `astrojs`: https://www.npmjs.com/package/@astrojs/check
* `Codespace` & `Codespaces`: https://github.com/features/codespaces
* `cookiecutter`: https://www.npmjs.com/package/cookiecutter
* `degit`: …
=> fix: add a few web terms

dictionaries/npm/src/npm.txt
- Add back `@arethetypeswrong/cli`.
- https://www.npmjs.com/package/@arethetypeswrong/cli
=> fix: Add @arethetypeswrong/cli

dictionaries/npm/cspell-ext.json, dictionaries/npm/cspell.json
Make sure the pattern only matches the left most quoted string.
=> fix: Adjust the NPM Scripts Patterns

dictionaries/software-terms/src/coding-terms.txt
Dictionary: _coding-terms_
Adds `ruleset` and `rulesets`.
"Rulesets" are a relatively newer GitHub feature:
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/creating-rulesets-for-a-repository
=> fix: add ruleset(s) to coding-terms

dictionaries/npm/src/npm.txt
- add `pinia`
- [pinia - npm](https://www.npmjs.com/package/pinia)
=> fix: Add pinia to npmjs

dictionaries/software-terms/src/coding-compound-terms.txt
- Use `Goog` to minimize false negatives.
=> fix: Use `Goog` to minimize false negatives.

dictionaries/software-terms/src/coding-terms.txt
- Add `docSearch` to coding-terms.txt
=> fix: Add `docSearch` to coding-terms.txt

package.json
=> chore: Update pnpm version

dictionaries/cspell/package.json, dictionaries/gis/package.json, dictionaries/mk/package.json, dictionaries/pokemon/package.json
=> fix: Fix dictionary package info

scripts/lib/packageInfoToMarkdown.mjs
=> chore: Remove small since it does nothing

dictionaries/aws/cspell-ext.json
Dictionary: _AWS_
This makes it easier to disable.
=> fix: Enable AWS at the top level

packages/en-freq/package.json, pnpm-lock.yaml, scripts/package.json
=> chore: Update commander cli

dictionaries/gaming-terms/src/game-development.txt, dictionaries/gaming-terms/src/godot.txt
Dictionary: gaming
- Add Godot terms
=> fix: Add Godot terms

dictionaries/bash/src/bash-words.txt, dictionaries/shell/src/command-words.txt, dictionaries/shell/src/miscellaneous-words.txt, dictionaries/shell/src/shell-zsh-words.txt
Note: I was not sure how flags should be added. Please advise.
Add Bash, Zsh and Shell related terms.
BASH_VERSINFO - https://www.bashsupport.com/bash/variables/bash_versinfo/
EPOCHREALTIME - https://www.bashsupport.com/bash/variables/epochrealtime/
SRANDOM - https://www.bashsupport.com/bash/variables/epochrealtime/
TIMEFORMAT - https://www.bashsupport.com/bash/variables/timeformat/
epochtime - https://www.bashsupport.com/zsh/variables/epochtime/
funcfiletrace - https://www.bashsupport.com/zsh/variables/funcfiletrace/
LOGCHECK - https://www.bashsupport.com/zsh/variables/logcheck/
TIMEFMT - https://www.bashsupport.com/zsh/variables/timefmt/
TTYIDLE - https://www.bashsupport.com/zsh/variables/ttyidle/
TTYIDLE - https://www.bashsupport.com/zsh/variables/ttyidle/
WATCHFMT - …
=> fix: Add Bash, Zsh and Shell related terms

dictionaries/google/cspell.json, dictionaries/google/package.json, dictionaries/google/samples/google.txt
Dictionary: google
Make a sample directory and use the google dictionary to spell check it.
=> test: Improve google dict test

dictionaries/google/src/misc.txt
Dictionary: google
- Add TensorBoard to google dict
=> fix: Add TensorBoard to google dict

dictionaries/companies/dict/companies.txt, dictionaries/companies/src/companies.txt, dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: `companies`, `softwareTerms`, `software-tools`
Added Infisical to relevant dictionaries. Infisical is an open-source secrets manager with widespread adoption.
Tagging @Jason3S for visibility!
https://github.com/Infisical/infisical
=> fix: add `Infisical` dicts

dictionaries/en_US/src/en_US.txt
Adds "neglection" to the en_US dictionary
- <https://www.merriam-webster.com/dictionary/neglection>
=> fix(en_US): add neglection

dictionaries/gl_ES/package.json
Dictionary: _gl_ES_
Prepare to publish
=> chore: prepare to publish gl_ES

dictionaries/hy/cspell-ext.json
=> chore: Adjust the dictionary name.

dictionaries/gl_ES/README.md
Dictionary: `gl-es` (`gl_ES`)
Update `README.md` to fix title and add acknowledgements.
`N/A`
=> fix: update `readme.md` to fix title and add contributors (`gl_ES`)

dictionaries/filetypes/src/filetypes.txt
Dictionary: filetypes
[nupkg](https://fileinfo.com/extension/nupkg)
=> fix: Add nupkg

dictionaries/gl_ES/README.md, dictionaries/gl_ES/checksum.txt, dictionaries/gl_ES/cspell-tools.config.yaml, dictionaries/gl_ES/dict/gl_ES.trie, dictionaries/gl_ES/samples/ausencias.txt, dictionaries/gl_ES/src/additional_words.txt
Dictionary: `gl-es` (`gl_ES`)
Add `additional_words.txt` file to `gl-es` dictionary. This change requires a new release of the dictionary.
`N/A`
=> feat: add additional words configuration file to `gl-es` dictionary

CONTRIBUTING.md
Adding where to propose the words a bit more in detail
- https://github.com/streetsidesoftware/cspell-dicts/issues/4047
=> docs(CONTRIBUTING.md): proposing words

dictionaries/fullstack/src/fullstack.txt
add `urlset`
- https://www.sitemaps.org/protocol.html#urlsetdef
=> fix(fullstack.txt): urlset

CONTRIBUTING.md
Explain what to do about multiple words PRs
- https://github.com/streetsidesoftware/cspell-dicts/issues/4047
=> docs(CONTRIBUTING.md): about multiple words

dictionaries/fullstack/src/fullstack.txt
add `changefreq`
- https://www.sitemaps.org/protocol.html#urlsetdef
=> fix(fullstack.txt): changefreq

dictionaries/cpp/cspell-tools.config.yaml, dictionaries/cpp/dict/cpp.txt, dictionaries/cpp/samples/cpp.txt, dictionaries/cpp/src/exclude-terms.txt
=> fix: Remove misspelling from cpp dict

package.json, pnpm-lock.yaml
=> chore: Update globals to 16

dictionaries/fullstack/src/fullstack.txt
Dictionary: Fullstack
Add `pocketbase` which is receiving more and more traction in the Headless CMS community
_Note: I would have put it into the name library but the project is named PocketBase, therefore this is more for the devs, not sure if that makes sense to add it here, but could be moved later if needed -> It shall also not be accepted and I can create it locally_ 
- https://github.com/pocketbase/pocketbase?tab=readme-ov-file#use-as-a-go-frameworktoolkit
=> fix(fullstack.txt): pocketbase

dictionaries/en_shared/src/shared-additional-words.txt
Dictionary: dictinaries/en_shared/src/shared-additional-words.txt
en_US dictionary doesn't have these words, and many documentation projects use en_US as the primary language.
=> fix: add words to shared-additional-words.txt

dictionaries/software-terms/src/coding-terms.txt, dictionaries/software-terms/src/software-terms.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary:
- software-tools.txt
- software-terms.txt
https://github.com/google/yamlfmt/blob/928ce33e9afa338486d889549fc78e6b7feabeaf/docs/config-file.md
Added some major software tools and options that I frequently use.
- [dprint](https://github.com/dprint/dprint)
- [Tailscale](https://tailscale.com/)
- [yamlfmt](https://github.com/google/yamlfmt)
- [indentless](https://github.com/google/yamlfmt/blob/928ce33e9afa338486d889549fc78e6b7feabeaf/docs/config-file.md)
=> fix: Add software tool names and options

dictionaries/software-terms/src/software-tools.txt
Dictionary: software-tools.txt
Added some tool names frequently used in the automotive industry, etc.
- [Codebeamer](https://codebeamer.com/)
- [esmini](https://github.com/esmini/esmini)
- [Jama](https://www.jamasoftware.com/)
- [Polarion](https://polarion.plm.automation.siemens.com/)
=> fix: Add software tools

dictionaries/cpp/cspell-tools.config.yaml, dictionaries/cpp/dict/cpp-legacy.txt, dictionaries/cpp/dict/cpp.txt, dictionaries/golang/cspell-tools.config.yaml, dictionaries/python/cspell-tools.config.yaml, dictionaries/ruby/cspell-tools.config.yaml, dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/src/software-terms.txt
=> fix: Add memo and nano to software terms

dictionaries/en-common-misspellings/dict-en.yaml
Dictionary: en-common-misspellings/dict-en.yaml
add `programatic->programmatic`
- [programmatic](https://en.wiktionary.org/wiki/programmatic)
=> feat: add `programatic->programmatic`

dictionaries/en_shared/src/shared-additional-words.txt, dictionaries/software-terms/src/software-terms.txt
Dictionary: software-terms.txt
Added some computing/software-related terms.
- [clothoid/clothoids](https://en.wiktionary.org/wiki/clothoid)
- [freespace(freeSpace)](https://docs.nvidia.com/drive/driveworks-3.5/dwx_freespace_detection_sample.html)
- [multirate](https://en.wiktionary.org/wiki/multirate)
- [polyline/polylines](https://en.wiktionary.org/wiki/polyline)
- [raytrace/raytracing(rayTrace/rayTracing)](https://developer.nvidia.com/rtx/raytracing/dxr/dx12-raytracing-tutorial-part-1)
- `chore:` - for changes that do not impact the content of …
=> fix: add computing/software-related terms

dictionaries/gaming-terms/src/unity.txt
=> fix: Update unity.txt, fix comment

dictionaries/software-terms/src/software-tools.txt
Dictionary: software-tools.txt
Added some software tool names.
- [spdlog](https://github.com/gabime/spdlog)
- [PlantUML](https://plantuml.com/)
- [Zellij](https://github.com/zellij-org/zellij)
- [zoxide](https://github.com/ajeetdsouza/zoxide)
- [Miniconda](https://www.anaconda.com/docs/getting-started/miniconda/main)
- [GEOS](https://github.com/libgeos/geos)
=> fix: Add software tool names

dictionaries/en_shared/src/shared-additional-words.txt
Adds words from our custom dictionary that are also defined on Merriam-Webster, and online American English dictionary.
* [ethnicities](https://www.merriam-webster.com/dictionary/ethnicities) — see plural
* [gamification](https://www.merriam-webster.com/dictionary/gamification)
* [nonconsensual](https://www.merriam-webster.com/dictionary/nonconsensual)
* [nonparty](https://www.merriam-webster.com/dictionary/nonparty)
* [nonpersonal](https://www.merriam-webster.com/dictionary/nonpersonal)
* [photoshop](https://www.merriam-webster.com/dictionary/photoshop)
* [retargeting](https://www.merriam-webster.com/dictionary/retargeting)
* [upvoted](https://www.merriam-webster.com/dictionary/upvoted) - see verb …
=> fix: add words to dictionary

dictionaries/npm/src/npm.txt
Adds casl (CASL) to the npm list.
- [casl](https://www.npmjs.com/package/@casl/ability) — `@casl/ability` on npm is their most notable package
=> fix: add casl to npm

dictionaries/golang/src/allowed-terms.txt
Dictionary: `golang`
Add the common function name: `Msgf`  for interpolating variables into a base string printf style.
- https://pkg.go.dev/github.com/rs/zerolog#Event.Msgf
=> fix: Add Msgf to golang

dictionaries/docker/src/docker-words.txt
Dictionary: `docker`
Add dind (aka: Docker in Docker) to docker dictionary.
- https://hub.docker.com/_/docker
- https://www.docker.com/resources/docker-in-docker-containerized-ci-workflows-dockercon-2023/
=> fix: Add dind to docker

dictionaries/golang/src/allowed-terms.txt
Dictionary: `golang`
Add more build-oriented words to the golang dictionary.
- gcflags: https://pkg.go.dev/cmd/go
- netgo: https://pkg.go.dev/net
- osusergo: https://pkg.go.dev/os/user
=> fix: Add more build-oriented words to golang

dictionaries/aws/src/aws.txt
Dictionary: `aws`
Add [`corretto`](https://aws.amazon.com/corretto/) to aws dictionary.
- https://aws.amazon.com/corretto/
=> fix: Add corretto to aws

dictionaries/golang/cspell-tools.config.yaml, dictionaries/golang/src/additional-terms.txt, dictionaries/golang/src/allowed-terms.txt, dictionaries/golang/src/go-lib.txt
Dictionary: golang
The purpose of the source files used to make the go dictionary is not very clear. This PR adds a few more files to accept new terms.
=> chore: Add more source files for golang.

.github/workflows/build-dictionaries.yml, .github/workflows/lint.yml, .github/workflows/release-please.yml, .github/workflows/test.yml, .github/workflows/update-dependencies.yml, .github/workflows/update-dictionaries.yml
=> chore: stop unnecessary workflow runs

dictionaries/npm/src/npm.txt
Adds 3 npm packages that we're using in another project.
* https://www.npmjs.com/package/@types/xast
* https://www.npmjs.com/package/css-tree
* https://www.npmjs.com/package/grunt-svgmin
* https://github.com/svg/svgo/pull/2101
=> feat: add packages to npm

dictionaries/en_US/src/en_US.txt
Adds "neurodivergent" and "neurodiversity" to the en_US dictionary
- https://www.merriam-webster.com/dictionary/neurodivergent
- https://www.merriam-webster.com/dictionary/neurodiversity
- https://en.wikipedia.org/wiki/Neurodiversity
=> fix(en_US): add neurodivergent and neurodiversity

dictionaries/en_shared/src/shared-additional-words.txt
Add the word "initialisms"
https://www.grammarly.com/commonly-confused-words/acronym-vs-initialism
=> fix: add the word "initialisms" to en_shared

dictionaries/en_US/src/en_US.txt
Dictionary: en_US.txt
Lidar can be plural.
- https://en.wikipedia.org/wiki/Lidar
=> fix: add lidars to en_US

dictionaries/python/src/common_packages.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary:
- python.txt
- software-tools.txt
Added some tool names.
- [ruamel.yaml](https://pypi.org/project/ruamel.yaml/)
- [Bazel](https://bazel.build/)
- [ublox](https://github.com/KumarRobotics/ublox)
- [kubespec](https://github.com/aptakube/kubespec.dev)
- [Packagecloud](https://packagecloud.io/)
- [Alacritty](https://alacritty.org/)
=> fix: add tool names

dictionaries/docker/src/docker-words.txt, dictionaries/software-terms/src/software-terms.txt
Dictionary:
- docker-words.txt
- software-terms.txt
Added Docker-related words.
- [dockerenv](https://github.com/docker/docker-install/blob/a58a95743941082c432918f6030af61740a32d6b/verify-docker-install#L14)
- I can replace this with `.dockerenv` or remove it from `software-terms.txt` if necessary.
- [onlatest](https://github.com/docker/metadata-action?tab=readme-ov-file#flavor-input)
=> fix: add Docker-related words

dictionaries/en_US/checksum.txt, dictionaries/en_US/cspell-tools.config.yaml, dictionaries/en_shared/cspell-tools.config.yaml, dictionaries/en_shared/dict/acronyms.txt, dictionaries/en_shared/src/acronyms.txt
=> chore: Add Acronyms files to en_shared

dictionaries/en_GB-ise/README.md, dictionaries/en_GB-ise/package.json
Dictionary: _en_GB-ise_
fix references in the README.md
=> doc: Fix links in README.md

dictionaries/en_AU/cspell-tools.config.yaml, dictionaries/en_CA/cspell-tools.config.yaml, dictionaries/en_GB-ise/cspell-tools.config.yaml, dictionaries/en_GB-legacy/cspell-tools.config.yaml, dictionaries/en_GB/cspell-tools.config.yaml, dictionaries/en_US/src/acronyms.txt, dictionaries/en_shared/src/acronyms.txt, dictionaries/software-terms/src/computing-acronyms.txt
Dictionary: 
en_AU: add POTUS and BDSM acronym (via en_shared)
en_GB: add POTUS and BDSM acronym (via en_shared)
en_CA: add POTUS and BDSM acronym (via en_shared)
en_US: no changes
software-terms: add DRM
- **chore: cleanup en_US/src/acronyms.txt from duplicates**
- **feat: move BDSM acronym to en_shared**
- **feat: add POTUS acronym to en_shared**
- **feat: add DRM to software-terms dictionary**
- **chore: move IFTTT to en_US/src/legacy/en_US.txt**
- **chore: add definitions for acronyms**
- **chore: add directive to en_US/src/acronyms.txt**
NA
- …
=> fix: english acronyms

dictionaries/en_US/src/acronyms.txt, dictionaries/en_shared/src/acronyms.txt
Dictionary: _en_CA_, _en_GB*_, _en_AU_, _en_US_
- **feat: add shared acronyms for English dictionaries**
- **feat: Add acronyms for American English**
=> fix: add common English acronyms

dictionaries/software-terms/dict/computing-acronyms.txt
- **chore: add definitions for acronyms in software-terms/dict/computing-acronyms.txt**
- **feat: add computing acronyms to software-terms**
=> fix: add computing acronyms

dictionaries/software-terms/src/software-tools.txt
Mostly around OSes, desktop environments, and data storage.
=> fix: add software tools to software-terms dictionary

dictionaries/filetypes/src/filetypes.txt
Dictionary: _filetypes_
- ogg: Ogg file for audio
- tsv: Tab Separated Values
- fish: Fish shell script
=> fix: add more file types to filetypes dictionary

dictionaries/companies/package.json, dictionaries/companies/test.cspell.config.yaml
Dictionary: _companies_
Related to #4367 
=> test: Improve tests for Companies

dictionaries/en_US/src/additional_words.txt
=> fix(english): add « decluttering » word

dictionaries/en_GB-MIT/src/legacy/legacy.txt
=> fix: Add `rigueur` to en_GB-MIT

dictionaries/software-terms/cspell-corrections.yaml, dictionaries/software-terms/src/coding-terms.txt, dictionaries/software-terms/src/software-tools.txt
=> fix: Add a few coding terms

dictionaries/cspell/package.json, pnpm-lock.yaml
Dictionary: _dict-cspell-bundle_
Make sure the dictionary list matches CSpell v9
=> feat!: sync CSpell v9 dictionaries

dictionaries/software-terms/cspell-corrections.yaml
This PR sorts the new words added by #4437
- https://github.com/streetsidesoftware/cspell-dicts/pull/4437#discussion_r2086104834
=> chore: sort terms in software-terms/cspell-corrections.yaml

dictionaries/software-terms/src/software-tools.txt
Dictionary: `software-tools.txt`
Add "OpenTofu" to `software-tools.txt`.
[OpenTofu](https://opentofu.org/) is an open source fork of Terraform.
- https://opentofu.org/
=> fix: add 'OpenTofu' to software tools dictionary

dictionaries/golang/src/go-lib.txt
Dictionary: `go-lib.txt`
Add 'logrus' to common Go libraries dictionary
- https://pkg.go.dev/github.com/sirupsen/logrus
=> fix: add 'logrus' to common Go libraries dictionary

dictionaries/git/cspell-ext.json
Dictionary: _git_
When writing GitHub actions, it is common to user git terms.
=> fix: git - enable git dictionary in `.github`

.github/workflows/test.yml
=> chore: Bump tests to use Node 24

dictionaries/en-common-misspellings/cspell.json, dictionaries/en-common-misspellings/scripts/transform-crate-ci-typos.mjs, dictionaries/en-common-misspellings/src/crate-ci/typos/README.md, dictionaries/en-common-misspellings/src/fromCrateTypos/README.md, dictionaries/en-common-misspellings/src/fromCrateTypos/dict-en-gb.txt, dictionaries/en-common-misspellings/src/fromCrateTypos/dict-en-us.txt, dictionaries/en-common-misspellings/src/fromCrateTypos/dict-en.txt, dictionaries/en-common-misspellings/src/fromCrateTypos/softwareTerms.txt
=> chore: some minor fixes to the typos transformer

dictionaries/npm/dict/npm.txt, dictionaries/npm/src/npm.txt
Please add `borp` to the npm dictionary.
- https://www.npmjs.com/package/borp
=> fix: add `borp`

dictionaries/npm/dict/npm.txt, dictionaries/npm/src/npm.txt
Please add `pagefind` to the nm dictionary.
- https://www.npmjs.com/package/pagefind
=> fix: add `pagefind`

dictionaries/people-names/checksum.txt, dictionaries/people-names/dict/people-names.txt, dictionaries/people-names/src/names.txt
Dictionary: people names
Adds my name
- I exist
=> fix: add my name to dictionary

package.json, pnpm-lock.yaml
=> chore: Update inject-markdown

dictionaries/aws/dict/aws.txt, dictionaries/aws/src/aws.txt
Dictionary: aws
Add missing AWS related terms
- [awsvpc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking-awsvpc.html);
- [Bedrock](https://aws.amazon.com/bedrock/);
- [DocumentDB](https://docs.aws.amazon.com/whitepapers/latest/aws-overview/database.html#amazon-documentdb);
- [Fargate](https://aws.amazon.com/fargate/);
- [Keyspaces](https://docs.aws.amazon.com/whitepapers/latest/aws-overview/database.html#amazon-keyspaces);
- [MemoryDB](https://docs.aws.amazon.com/whitepapers/latest/aws-overview/database.html#amazon-memorydb-for-redis);
- [PrivateLink](https://aws.amazon.com/privatelink/);
- [Timestream](https://docs.aws.amazon.com/whitepapers/latest/aws-overview/database.html#amazon-timestream).
- `fix:` - for minor changes like adding words or fixing spelling …
=> fix: [aws] Add missing AWS related terms

dictionaries/npm/dict/npm.txt, dictionaries/npm/src/npm.txt
Add packages:
- headlessui
- remeda
- valibot
- [headlessui](https://www.npmjs.com/package/@headlessui/vue)
- [remeda](https://www.npmjs.com/package/remeda)
- [valibot](https://www.npmjs.com/package/valibot)
=> fix: add words in npm dictionary

dictionaries/docker/src/docker-words.txt
Dictionary: docker
Add missing Docker related terms
- [Dockerize](https://www.docker.com/blog/how-to-dockerize-react-app/);
- [Dockerized](https://docs.docker.com/build/ci/#docker-in-docker).
=> fix: [docker] Add missing Docker related terms

dictionaries/es_ES/src/additional_words.txt
Dictionary: es_ES
Add missing Spanish terms.
- [contenedorizar (and its derivatives)](https://x.com/RAEinforma/status/1361251612971438083).
=> fix: [es] Add missing Spanish terms

dictionaries/companies/dict/companies.txt, dictionaries/companies/src/companies.txt
Add missing companies
- [Verisec](https://www.verisecint.com/).
=> fix: [companies] Add missing companies

.github/actions/quick-setup/action.yaml, .github/actions/setup/action.yaml, .github/workflows/autofix.yml, .github/workflows/test.yml
=> chore: Use node 24.x for workflows

dictionaries/companies/dict/companies.txt, dictionaries/companies/src/companies.txt
=> fix: Update companies.txt

dictionaries/software-terms/dict/webServices.txt, dictionaries/software-terms/src/software-services.txt
=> fix: Update software-services.txt

dictionaries/en-common-misspellings/dict/dict-en.json, dictionaries/en-common-misspellings/src/dict-en.txt
Dictionary: English
Add:
- `remnat->remnant`
- `remnats->remnants`
=> fix: Add misspelling suggestion for `remnat->remnant`

dictionaries/en_shared/dict/shared-additional-words.txt, dictionaries/en_shared/src/shared-additional-words.txt
`disinvite` word
- https://www.collinsdictionary.com/dictionary/english/disinvite
=> fix: add disinvite 

dictionaries/software-terms/dict/software-tools.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: software tools
- Add 'ohmyzsh' and 'oh-my-zsh' to software tools list
=> fix: Add 'ohmyzsh' and 'oh-my-zsh' to software tools list

dictionaries/software-terms/dict/softwareTerms.txt, dictionaries/software-terms/src/coding-terms.txt
Add 'devContainers' to coding terms list
=> fix: Add 'devContainers' to coding terms list

dictionaries/software-terms/dict/software-tools.txt, dictionaries/software-terms/src/software-tools.txt
Dictionary: `software-tools`
Added `pixi`
[Pixi](https://pixi.sh/) is a next-gen package manager.
=> fix: add `pixi` to `software-tools`

dictionaries/python/dict/python.txt, dictionaries/python/src/python/python.txt
Dictionary: `python`
`reduceat` (local reduce) is a method in NumPy.
See <https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html>
- `feat:` - for a significant change like adding a whole new set of words to a
dictionary.
=> fix: add `reduceat` to `python`

dictionaries/data-science/dict/data-science.txt, dictionaries/data-science/src/data-science-terms.txt, dictionaries/python/dict/python.txt, dictionaries/python/src/python/python.txt
Dictionary: `python`, `data-science`
Added `meshgrid`. `meshgrid` is a function in `NumPy`, also a common term in data science.
<https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html>
=> fix: add `meshgrid` to `python` and `data-science`

dictionaries/filetypes/src/filetypes.txt
Dictionary: `filetypes`
Add `icns` extension for Apple Icon Image format.
- https://en.wikipedia.org/wiki/Apple_Icon_Image_format
=> fix: add `icns` to `filetypes`
