streetsidesoftware/cspell-dicts

de_DE/package.json
en_GB/package.json
en_US/package.json
es_ES/package.json
fr_FR/package.json
golang/package.json
html-symbol-entities/package.json
nl_NL/package.json
php/package.json
pl_PL/package.json
pt_BR/package.json
pt_PT/package.json
python/package.json
ru_RU/package.json
russian/package.json
sv/package.json

- Update devDependencies to use latest `cspell-tools` version.
Related to:
https://github.com/Jason3S/cspell-dicts/issues/4

fix(package.json) update devDependencies

---

CONTRIBUTING.md
README.md
cpp/README.md
de_DE/README.md
en_GB/README.md
en_US/README.md
es_ES/README.md
fr_FR/README.md
generator-cspell-dicts/README.md
generator-cspell-dicts/generators/app/templates/README.md
golang/README.md
html-symbol-entities/README.md
nl_NL/README.md
php/README.md
pl_PL/README.md
pt_BR/README.md
pt_PT/README.md
ru_RU/README.md
russian/README.md
sv/README.md

- Fix Markdown syntax issues from [markdownlint](https://github.com/DavidAnson/markdownlint)
- Improve generator template for `README.md` files.
MD006 - Consider starting bulleted lists at the beginning of the line
MD012 - Multiple consecutive blank lines
MD022 - Headers should be surrounded by blank lines
MD031 - Fenced code blocks should be surrounded by blank lines
MD032 - Lists should be surrounded by blank lines
MD040 - Fenced code blocks should have a language specified
MD042 - No empty links
- https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

docs() improve Markdown syntax

---

scripts/publish_dict.sh
scripts/publish_langs.sh

- Add missing quotes to the scripts to avoid errors
- Add missing shell command to the top of `publish_dict.sh`
Improve code quality by checking the scripts with [ShellCheck](https://github.com/koalaman/shellcheck)
These issues should be fixed with this Git commit:
```
In publish_dict.sh line 1:
echo Publish $1
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
^-- SC2086: Double quote to prevent globbing and word splitting.
In publish_dict.sh line 2:
cd $1 && npm run publish-patch
^-- SC2086: Double quote to prevent globbing and word splitting.
In publish_langs.sh line 19:
echo Running: ./scripts/publish_dict.sh $i
^-- SC2086: Double quote to prevent globbing and word splitting.
In publish_langs.sh line 20:
./scripts/publish_dict.sh $i
^-- SC2086: Double quote …
```

fix(scripts) add missing quotes

---

generator-cspell-dicts/package.json

- Update outdated `package.json`
- Update outdated Jest version
- Changed from `nsp check` to `npm audit`
- Remove `nsp` from `devDependencies`
Related to:
- https://github.com/Jason3S/cspell-dicts/issues/39

fix(generator): update outdated package.json

---

packages/latex/latex.txt

This PR adds more latex keywords.
*Note: Any idea what the sorting order of this file is? I can't seem to find the right command to sort. The closest I got is `LC_ALL=C sort --ignore-case` but that shows the alphanum before `\`..*

Add more latex keywords

---

packages/companies/companies.txt

These are the three official ways to write the name of Ghent University (https://www.ugent.be/)
(moved here from https://github.com/Jason3S/cspell/pull/76)

Add Ghent University

---

packages/cpp/cpp.txt
packages/en_US/en_us.txt
packages/medicalterms/medicalterms-en.txt

Cleaned up a few more i hit, removed some duplicates, and went through https://en.oxforddictionaries.com/spelling/common-misspellings for hits

Remove typos and duplicates in CPP/US

---

packages/elixir/elixir.txt

Hey, the defstruct keyword was missing from the elixir dictionary.

Add defstruct to elixir dictionary

---

packages/companies/companies.txt

We use these company names a lot in our documentation at Netlify.

Add companies

---

packages/companies/companies.txt

- Noticed various spelling issues in the previous Git commits.
- Added more companies to the list, and improved the accuracy of the items.
- Fix spelling mistakes
- Change `Whatsapp` to `WhatsApp`
- Change `Xing` to `XING`
- Change `Vimeo` to `Vimeo, Inc.`
- Change `Unpkg` to `unpkg`
- Change `Undraw` to `unDraw`
- Change `Reddit` to `Reddit, Inc.`
- Change `Reactstrap` to `reactstrap`
- Even while `reactstrap` is a JavaScript library, not a company...
- Add more companies
- Add `Automattic Inc.`
- Add `Snap Inc.`
- Add `Liberty Media Corporation`
- Fix spelling mistakes
- Change `Verisign` to `Verisign, Inc.`
- Remove duplicate
- Remove `VeriSign`
- Maintain list order
- Run `Sort Lines Ascending` command with VS Code

Improve dictionary spellings. add more companies

---

packages/cpp/cspell-ext.json

Updates cpp's ignoreRegExpList to ignore hex integers.
Fixes #126

Support ignoring single quote in c++ hex numbers (#126)

---

packages/en_US/src/en_US.txt
packages/fullstack/fullstack.txt

I did not see any template for PRs in the contributing guidelines. Please let me know if I didn't do this  correctly.
Copied wordsEnGb.txt to en_US.txt:
* preallocate
* preallocated
* preallocates
* preallocating
* preallocation
* preallocations
* subnet
* subnet's
* subnets
Added `polyfill` to en_US.txt and fullstack.txt (polyfills already existed in both)

Add words to en_US.txt and fullstack.txt

---

packages/software-terms/softwareTerms.txt

Add `slugify`
I think it best fits the Software Terms dict.
The term is commonly used, and there are packages and services named `slugify`, which helps in converting a string to a human readable valid url

Add slugify

---

packages/software-terms/softwareTerms.txt

Found that `map` entry is added twice

Remove duplicate "map" entry

---

packages/software-terms/softwareTerms.txt

Adds `memoize` and its variants to the software terms dict as discussed here #157

Add memoize and its variants

---

packages/typescript/typescript.txt

Removes memoize from Typescript dict as discussed here #157 
I don't know why zpass has been automatically removed and added (I'm a bit in a hurry and did the change on GitHub website 🙈)

Remove memoize from Typescript dict

---

packages/software-terms/softwareTerms.txt

debounce was already added, but debounced was missing. 
Often times it is used in naming functions like `linesChangedDebounced` for instance.

Add debounced

---

packages/python/python.txt

Adding Python datetime [strftime](https://docs.python.org/3/library/datetime.html#datetime.date.strftime) and [strptime](https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime)

Add Python strftime and strptime

---

packages/haskell/haskell.txt

Was playing around with `find . -type f -name "*.txt" -exec sh -c "sort -m '{}' | uniq -d" \;`. The other one with a bunch of duplicates is the en-GB dictionary

chore: Remove duplicates in Haskell

---

packages/companies/companies.txt
packages/css/css.txt
packages/fullstack/fullstack.txt
packages/html/html.txt
packages/software-terms/softwareTerms.txt

Not everything in the dictionary is general to everything, but there were some missing HTML attributes/property names and some general software terms that made sense in the various dictionaries.
One part I wasn't sure about is for words that have to do with SVG properties/attributes. I put them in the HTML dictionary, but maybe it should have its own

Port over words from aria-practices

---

packages/html/cspell-ext.json

Make the patterns global and simplify the RegExp.
`\b` added to prevent false matches.
`[^"]` use to match everything till the next `"`
`/gi` to make sure it is global and case insensitive.

fix: http - make the aria patterns global

---

packages/companies/companies.txt

I had these for the longest time in my local dictionary
Having them in the global dictionary would make much more sense
See https://en.wikipedia.org/wiki/Datadog and https://www.datadoghq.com

fix: add datadog company name and stock symbol

---

README.md
cSpell.json
generator-cspell-dicts/package.json
packages/de_DE/README.md
packages/fr_FR/README.md

Had a warning is VSCode around the empty URL, so I just reran `npm init -y` to clean up to the latest schema. Manually updated the repository afterwards from `git+ssh` to `git+https` format

chore: Run npm init on generator-cspell-dicts

---

dictionaries/html/html.txt

Slowly working through the new https://github.com/mdn/content and this was the first one that I saw that was probably "missing"
I'll probably try and gather others up later in a larger batch if I find more
Wasn't sure if this should also go in `packages/html` too or not

fix: Add longdesc to HTML dict

---

dictionaries/python/python.txt
packages/python/python.txt

noticed it in the Scientific and Medical dictionaries, but thought it made sense here

fix: Add pytest to Python dictionaries

---

dictionaries/haskell/cspell-ext.json

Fix for [Doesn't understand the contraction "doesn't" in Haskell files. · Issue #707 · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/issues/707)

fix:Haskell ' breaking contractions

---

dictionaries/software-terms/softwareTerms.txt
dictionaries/typescript/typescript.txt

It cause problems for us since we use this word inside our README.md

fix: Move 'transpile' to softwareTerms dictionary

---

dictionaries/en_US/src/en_US.txt

Looks like constitutional was missing the first 't' in the en_US dictionary.

en_US spelling of constitutional

---

dictionaries/software-terms/softwareTerms.txt

"SDK" stands for software development kit.

Add "sdk" and "sdks" to software terms dictionary.

---

dictionaries/software-terms/softwareTerms.txt

Add "Unlicense" to software terms dictionary.

---

dictionaries/dotnet/dotnet.txt

This is the extension of the package manifest file for Universal Windows Platform apps.

Add "appxmanifest" to dotnet dictionary.

---

dictionaries/npm/npm.txt

.nvmrc is the name of the configuration file for Node Version Manager.

Add "nvmrc" to npm dictionary.

---

dictionaries/filetypes/filetypes.txt

"appxmanifest" is written as "AppxManifest" in Universal Windows Platform (UWP) build config files.

Add "appx" to file types dictionary.

---

dictionaries/dotnet/dotnet.txt

This is part of a Microsoft namespace for popular VSCode extensions.

Add "dotnettools" to dotnet dictionary.

---

dictionaries/filetypes/filetypes.txt

Add "altform," "targetsize," and "unplated."

Add icon filename verbiage to file types dict.

---

dictionaries/dotnet/dotnet.txt

"NetFx" is an abbreviation for .NET Framework.
"pdbonly" is a value of the build property DebugType.
"Toolchain" is part of the build property UseDotNetNativeToolchain.

Add words from msbuild properties to dotnet dict.

---

dictionaries/dotnet/dotnet.txt

Add "altform," "targetsize," and "unplated."

Add icon filename verbiage to dotnet dictionary.

---

dictionaries/dotnet/dotnet.txt

"appxmanifest" is written as "AppxManifest" in Universal Windows Platform (UWP) build config files.

Add "Appx" to dotnet dictionary.

---

dictionaries/python/python.txt

Add "bandit," "black," "flake8," "gjslint," "isort," "mccabe," "pep8," "pep257," "prospector," "pycodestyle," "pydocstyle," "pyflakes," "pylama," "pylint," and "radon."

Add some linters to python dictionary.

---

dictionaries/python/python.txt

Add "appdirs," "pipenv," "pipfile," "pipx," "prereleases," "venv," and "virtualenv."

Add some pipenv terminology to python dictionary.

---

dictionaries/public-licenses/cspell-ext.json
dictionaries/public-licenses/cspell.json
generator-cspell-dicts/generators/app/templates/cspell-ext.json

- Add `"public-licenses"` to `"dictionaries"` instead of `"languageSettings"`
- fix dictionary definition to use `path` instead of `file`

fix: Make it easier to turn off the public-licenses dictionary

---

dictionaries/dotnet/dotnet.txt

This is a variable used in the manifest of a UWP (Universal Windows Platform) app that resolves to the filename of the executable upon building.

Add "targetnametoken" to dotnet dictionary.

---

dictionaries/software-terms/softwareTerms.txt

"ghcr" stands for GitHub Container registry, which is where GitHub Packages are hosted. "githooks" are commit hooks used by Git.

Add "ghcr" and "githooks" to software terms dict.

---

dictionaries/filetypes/filetypes.txt

These are portions of language codes that can end up in file extensions. "cyrl" means "Cyrillic," "hant" refers to the Traditional script (e.g., of Chinese), and "latn" means "Latin."

Add "cyrl," "hant," and "latn" to file types dict.

---

dictionaries/dotnet/dotnet.txt

"NETFX" is an abbreviation for .NET Framework commonly found in .csproj files. Since .csproj files are themselves XML files and cspell disallows compound words by default in XML files, the existing dictionary entry "NetFx" does not match "NETFX."

Add "NETFX" to dotnet dictionary.

---

dictionaries/software-terms/softwareTerms.txt

It is more of a specific marketing thing, but I say it added into the custom words on another repo

fix: Add Hacktoberfest to software terms

---

dictionaries/python/python.txt

"pow" and "pytest" both appeared twice in a row.

Remove some duplicates from python dictionary.

---

dictionaries/python/python.txt

Mypy offers a disallow_any_unimported option.

Add "unimported" to Python dictionary.

---

dictionaries/python/python.txt

These are inline directives to disable linters.

Add "noqa" and "nosec" to Python dictionary.

---

dictionaries/software-terms/softwareTerms.txt

Mega-Linter has a configuration option named `FILEIO_REPORTER`.

Add "fileio" to software terms dictionary.

---

dictionaries/software-terms/softwareTerms.txt

Add "dockerd" and "setuptool" from dockerd-rootless-setuptool.sh.

Add some Docker words to software terms dictionary

---

dictionaries/bash/bash-words.txt

SCRIPTDIR is the path to the current script in ShellCheck.

Add "SCRIPTDIR" to Bash dictionary.

---

dictionaries/software-terms/src/software-terms.txt

Add "copypaste," "Exts," "medicalterms," and "streetsidesoftware."
"Copypaste" is the key Mega-Linter uses for copy-paste detectors.
"Exts" is an abbreviation for "extensions" used by jscpd.
"Medicalterms" is the name of a cspell dictionary.
"Streetsidesoftware" is the name of the organization that houses cspell.

Add some terms to software terms dictionary.

---

dictionaries/software-terms/src/software-tools.txt

"mongod is the primary daemon process for the MongoDB system."
~ https://docs.mongodb.com/manual/reference/program/mongod/

Add "mongod" to software terms dictionary.

---

dictionaries/software-terms/src/software-tools.txt

MegaLinter is a linter aggregator. See https://megalinter.github.io/ for more details.

Add "MegaLinter" to software tools dictionary.

---

.github/workflows/build-dictionaries.yml
.github/workflows/cspell-action.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/update-dependencies.yml

- Unpin the version to minimize Dependabot PRs
- Use built-in caching based off off actions/cache

chore: use setup-node caching for yarn

---

dictionaries/html/html.txt

The old compile tool split on `-` before adding words to the list. The new one does not, so words need to be added explicitly.

fix: add `aria-*` terms to the list.

---

dictionaries/css/css.txt

Adds the minmax function from CSS grid
https://developer.mozilla.org/en-US/docs/Web/CSS/minmax()

fix(css): add minmax

---

dictionaries/typescript/cspell-ext.json
dictionaries/typescript/samples/sample.tsx

Related to: [Spell Checker wants to check regex flags · Issue #1720 · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/issues/1720)

fix: Ignore RegExp flags in TypeScript/JavaScript

---

dictionaries/npm/npm.txt

This adds the npm markdownlint package to the npm dictionary.

Add markdownlint to npm

---

dictionaries/software-terms/src/network-os.txt
dictionaries/software-terms/src/network-protocols.txt

This adds 2 network dictionaries:
1) network protocols, these may overlap with other dictionaries, LMK if that is a problem
2) network os, The operating system acronyms for several network devices from network vendors
Let me know what the next steps are and how I can help

Add network dictionaries

---

dictionaries/software-terms/src/software-tools.txt

CSharpier is an auto-formatter in the style of Prettier for C#. Since the first two letters are both uppercase, CSpell sometimes tokenizes "Sharpier" as a separate word.

Add "CSharpier" and "Sharpier" to software tools

---

package.json

It is almost never necessary to rebuild all the dictionaries. Rename `build` to `build-all` to prevent accidental building of the dictionaries.

ci: rename `build` to `build-all`

---

dictionaries/html/html.txt

Used in the robots meta tag: https://en.wikipedia.org/wiki/Noindex

Add noindex to the html dictionary

---

dictionaries/companies/src/companies.txt
dictionaries/software-terms/src/software-terms.txt
dictionaries/software-terms/src/software-tools.txt

**Added:**
- Atlaskit
- Atlassian
- Halp (could be problematic for misspellings of "help" - LMK if this is allowed)
- Jira
- Sourcetree
- Trello
**Relocated product names to 'software-tools'**
- Bitbucket
- Jira

Add Atlassian terms to dictionaries

---

dictionaries/cpp/cpp.txt

Noticed the "requst" given as a suggestion for a typo "reqest" and traced it back to this dictionary. Saw a few around it that also looks like typos

fix: cpp typos

---

dictionaries/cpp/cspell-ext.json
dictionaries/cpp/cspell.json
dictionaries/csharp/cspell-ext.json
dictionaries/csharp/cspell.json
dictionaries/golang/cspell-ext.json
dictionaries/golang/cspell.json
dictionaries/python/cspell-ext.json
dictionaries/python/python.txt

BREAKING CHANGE
Do not set `allowCompoundWords: true` for
- cpp, c
- csharp
- go
- python
To add it back, use:
```json
"languageSettings": [
{
"languageId": "c,cpp,csharp,go,python",
"allowCompoundWords": true
}
]
```

feat!: Remove `allowCompoundWords: true`

---

dictionaries/fullstack/fullstack.txt

Add "br," "compress," "deflate," "gzip," "identity," and "zstd."

Add HTTP Accept-Encoding values to full stack dict

---

dictionaries/npm/npm.txt

"enumtype" is a type from the popular ts-interface-checker package.
"typegoose" is the name of a popular package.

Add "enumtype" and "typegoose" to npm dictionary

---

dictionaries/fr_FR/cspell-ext.json
dictionaries/fr_FR_90/cspell-ext.json

**Note:** this is a semi breaking change for code.
To turn off cases sensitivity for a file type:
**`cspell.json`** turn off for JavaScript
```json
{
"languageSettings": [
{
"languageId": "javascript",
"locale": "fr,fr_FR",
"caseSensitive": false
}
]
}
```

feat: Make sure French is case and accent sensitive by default.

---

dictionaries/python/src/python/python.txt

This is a function in the `re` module.

Add "fullmatch" to Python dictionary

---

dictionaries/npm/npm.txt

Add "jscpd," "kucherenko," and "vercel," which are the names of some popular npm packages or their GitHub organization.

Add some popular npm packages to npm dictionary

---

dictionaries/npm/npm.txt

testdouble is a popular test double library.

Add "testdouble" to npm dictionary

---

dictionaries/html/html.txt

Adds the `preconnect` link type
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preconnect

fix(html): add preconnect

---

dictionaries/rust/rust.txt

Hi, thank you for publishing great tools.
It turns out that "dedup", a name of the de-duplication method in std::vec::Vec, is treated as an error in spell checking. This PR fixes this problem by adding "dedup" to the dictionary.
Ref: https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.dedup

[Rust] Add "dedup", a method name in std::vec::Vec

---

dictionaries/haskell/cspell-ext.json
dictionaries/haskell/cspell.json
dictionaries/haskell/samples/fib.hs

Support more contractions: https://github.com/streetsidesoftware/vscode-spell-checker/issues/707#issuecomment-1172980816

fix: Update `'` parsing in Haskell

---

dictionaries/en_US/src/additional_words.txt

https://en.wiktionary.org/wiki/negatable

fix: add `negatable` to en-US

---

dictionaries/cpp/src/cpp.txt
dictionaries/filetypes/filetypes.txt

Adds HEIF file types
https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding
I wasn't exactly sure which dictionary to add these to, please let me know if they should be moved to another dict.

feat: add heif types

---

dictionaries/software-terms/src/software-terms.txt
dictionaries/software-terms/src/software-tools.txt

Refer to LinuxServer's [Alpine Docker image](https://github.com/linuxserver/docker-baseimage-alpine/pkgs/container/baseimage-alpine), for example.

Add linuxserver and baseimage to dictionaries

---

dictionaries/companies/src/companies.txt
dictionaries/software-terms/src/software-tools.txt

Adds the following tech companies:
```
Expensify
HelloSign
Mailtrap
Mixpanel
SmartyStreets
```

Add several tech companies

---

dictionaries/en_US/src/additional_words.txt

Dictionary: `en_US`
Add `backtick` and `backticks`.
- [Backtick - Wikipedia](https://en.wikipedia.org/wiki/Backtick)

fix: Add backtick to English dictionary

---

dictionaries/da_DK/README.md

danish dic
Dictionary: danish
this url is not exist any more [http://www.stavekontrolden.dk/main/top/index.php)](http://www.stavekontrolden.dk/main/top/index.php) , you can check it here : 
https://web.archive.org/web/20190913023653/http://www.stavekontrolden.dk/main/top/index.php , the new fix always shows the home page of that website.

fix: fix url for danish spell checker

---

dictionaries/software-terms/src/software-terms.txt

Add the word "chainable". As in "The methods on this class all return `this`, this means they are chainable". 
I was tempted to add it to en-gb and en-us but after a quick Google the only website I can find it on is Wiktionary.
https://en.wiktionary.org/wiki/chainable
https://www.thefreedictionary.com/chainable
https://dictionary.cambridge.org/spellcheck/english/?q=chainable
https://www.merriam-webster.com/dictionary/chainable
https://www.dictionary.com/misspelling?term=chainable

fix: Add "chainable" to the software terms

---

dictionaries/software-terms/src/software-terms.txt

- LDAP is too common of a term is software security discussions to be only included in the network protocol dictionaries.
- Adjusts #1397
- Detected during dictionary update of CSpell: https://github.com/streetsidesoftware/cspell/pull/3495
- [Lightweight Directory Access Protocol - Wikipedia](https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol)

fix: add back `ldap` to software terms

---

dictionaries/software-terms/src/software-tools.txt

`cmake` is a popular tool.
- https://cmake.org

fix: Add `cmake` to software tools

---

dictionaries/software-terms/src/software-terms.txt
dictionaries/typescript/typescript.txt

Dictionary:
* dictionaries/software-terms/src/software-terms.txt
* dictionaries/typescript/typescript.txt (happy to drop this)
Remove three entries from `software-terms.txt`

fix: Remove typos from software terms

---

dictionaries/software-terms/src/software-terms.txt

Adds "captchas" (plural of "captcha")
N/A

fix: Add "captchas" to software terms

---

dictionaries/de_DE/cspell-ext.json
dictionaries/de_DE/cspell.json
dictionaries/de_DE/samples/alternate_spelling.md

Dictionary: de_DE
fixes #1176
BREAKING: This change requires CSpell 6.12.0 or higher.
- https://github.com/streetsidesoftware/cspell/issues/3590
- https://github.com/streetsidesoftware/cspell/issues/3592
- https://github.com/streetsidesoftware/vscode-spell-checker/issues/2066
- https://github.com/streetsidesoftware/cspell-dicts/issues/1176

feat!: Support Umlaut alternatives

---

dictionaries/software-terms/src/software-tools.txt

See [Checkov's documentation](https://www.checkov.io/1.Welcome/Quick%20Start.html).

fix: Add "Checkov" to the software tools dict

---

dictionaries/software-terms/src/software-terms.txt

Adds pixelated to software-terms. Also adds the British spelling (pixellated) 
- https://en.wikipedia.org/wiki/Pixelation
- https://www.dictionary.com/browse/pixelated
- https://www.thefreedictionary.com/pixelated
- https://dictionary.cambridge.org/us/dictionary/english/pixelated

fix: add pixelated and pixellated to software-terms

---

dictionaries/software-terms/src/software-terms.txt

`deref` is a common shortening of `dereference` in code.
- [WeakRef.prototype.deref() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef/deref)

fix: add `deref` - dereference

---

dictionaries/css/dict/css.txt
dictionaries/css/src/css.txt

Ensure the new version is compatible with the old one.

fix: Adjust the CSS dictionary to be backwards compatible.

---

dictionaries/en_GB/src/additional_words.txt

Dictionary: en_gb
Add the word Aruban
- [Wikipedia Article on Aruba](https://en.wikipedia.org/wiki/Aruba)

fix: Add to Aruban en_gb

---

dictionaries/gaming-terms/package.json

Make Gaming Terms public so it can be published.
Fix: #1695

fix: Publish Gaming Terms

---

dictionaries/en_US/src/additional_words.txt

Dictionary: en-US
Adds the word `infographic` to the list of additional words in the en-US dict
[Merriam-Webster](https://www.merriam-webster.com/dictionary/infographic)

add infographic to list of english words

---

dictionaries/en_GB/src/additional_words.txt

Dictionary: en_GB
Closes #193
Added British Software Terms
Used https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/inspection-guides/glossary-computer-system-software-development-terminology-895 as a base for American terms then Cross referenced them with a dictionary to see if a British counterpart existed.

fix: Add British Software Terms

---

dictionaries/fullstack/fullstack.txt

Add `facebook` and `instagram`
From this issue https://github.com/streetsidesoftware/cspell-dicts/issues/1700#issuecomment-1360884498

fix: Add facebook and instagram to fullstack.txt

---

dictionaries/software-terms/src/software-tools.txt

"mongod" was originally added to the software terms dictionary in #761 but then removed in #1419.
- "mongod is the primary daemon process for the MongoDB system." ~ https://docs.mongodb.com/manual/reference/program/mongod/

fix: Add "mongod" to software terms dictionary.

---

dictionaries/css/src/css.txt

Currently the [`overscroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) property isn't recognized and the `overscroll` part is reported as a misspelling.

Add `overscroll` to the CSS dictionary

---

dictionaries/software-terms/src/software-terms.txt

Dictionary: softwareTerms
Adds 'idempotence' and 'toolchains' to match existing terms 'idempotent' and 'toolchain'
none
fixes: #1824

fix: Add idempotence and toolchains to softwareTerms

---

dictionaries/en_GB/package.json
package.json
yarn.lock

We used `rimraf` to delete files using glob patterns, this is no longer supported.

chore: use `shx` instead of `rimraf` to delete files.

---

dictionaries/en_GB-MIT/README.md
dictionaries/en_GB/README.md
dictionaries/en_US/README.md
dictionaries/fr_FR/README.md
dictionaries/fr_FR_90/README.md
generator-cspell-dicts/generators/app/templates/README.md

This PR starts the process of adding footers to all the dictionaries:
```markdown
<br/>
---
<p align="center">
Brought to you by <a href="https://streetsidesoftware.com" title="Street Side Software">
</a>
</p>
```
<br/>
---
<p align="center">
Brought to you by <a href="https://streetsidesoftware.com" title="Street Side Software">
</a>
</p>

fix: Add footer to dictionary README.md

---

dictionaries/cpp/src/cpp.txt
dictionaries/en-common-misspellings/dict-en.yaml
generator-cspell-dicts/generators/app/index.js

Dictionary: `en-common-misspellings`
Even though `programing` is a word, it is no longer considered correct.
See: [Ngram: programing vs programming](https://books.google.com/ngrams/graph?content=programming%2Cprograming%2Ccoding&year_start=1900&year_end=2019&corpus=en-2019&smoothing=3)
<a href="https://books.google.com/ngrams/graph?content=programming%2Cprograming%2Ccoding&year_start=1900&year_end=2019&corpus=en-2019&smoothing=3"><img width="1554" alt="Image, programing vs programming" src="https://user-images.githubusercontent.com/3740137/219025193-ed3008ce-92f1-4fb7-bfca-98770ec04279.png"></a>

fix: Encourage the correct spelling of `programming`.

---

dictionaries/software-terms/src/software-tools.txt

Dictionary: software tools
OXSecurity is the organization that MegaLinter's Docker images are hosted under.
- https://github.com/oxsecurity/megalinter
- https://hub.docker.com/r/oxsecurity/megalinter

Add "OXSecurity" to software tools dictionary

---

dictionaries/fullstack/src/fullstack.txt

Add the `noindex` since it may be used in `js` and `ts` files
[- _Any source references._](https://developers.google.com/search/docs/advanced/crawling/block-indexing?hl=fr)

fix: Add `noindex` to fullstack.txt

---

dictionaries/fonts/fonts.txt

Dictionary: ```fonts```
Adds Missing Words
* Ysabeau
*  Busorama

fix: Adds missing words to Fonts and fixes oreder

---

dictionaries/npm/src/npm.txt

Dictionary: ```npm```
Adds words to NPM
* flatpickr
* jarallax
* mapboxgl
* jsbundling
* muuri
* pagy
* esbuild
* mkcert

fix: Adds some missing Words to NPM

---

dictionaries/software-terms/src/software-services.txt

Dictionary: ```software-services```
Adds  Missing word
* imessage
https://github.com/streetsidesoftware/cspell-dicts/pull/1938

fix: Adds missing words to `software-services`

---

dictionaries/companies/src/companies.txt

Dictionary: ```companies```
Adds missing words to companies
* viber
* waze
* imgix
* moovit
* cdnjs
* hulu
* papaki
* imessage
Fixes word order

fix: Adds missing words to `companies`

---

dictionaries/css/src/css.txt

Dictionary: ```css```
Adds Missing words to CSS 
* clig
* calt
* lnum
* tnum
* zindex
Fixes order

fix: Adds Missing words to `CSS` and fixes order

---

dictionaries/win32/src/win32.txt

Dictionary: win32
Add "LTSC" and "Nanoserver." Both terms appear in the container names of Windows base images.
LTSC stands for Long-Term Servicing Channel.
Nanoserver is the name of a Windows container base image.
- https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images

Add "LTSC" and "Nanoserver" to win32 dictionary

---

dictionaries/python/src/python/python.txt

Pyright is a static type checker for Python.
Dictionary: Python
Add "pyright."
- https://github.com/microsoft/pyright

fix: Add "pyright" to Python dictionary

---

dictionaries/sql/cspell-ext.json
dictionaries/sql/cspell.json

Related to https://github.com/streetsidesoftware/vscode-spell-checker/issues/2576

feat: Enable "sql" in VS Code by default

---

dictionaries/software-terms/src/software-terms.txt

Add "arbitrary" and "arbitraries." In property-based testing, arbitraries generate random input values.
- https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck-Arbitrary.html
- https://github.com/dubzzz/fast-check/blob/main/packages/fast-check/documentation/Arbitraries.md

Fix: Add "arbitrary(-ies)" to software terms dictionary

---

dictionaries/python/src/python/python.txt

Dictionary: Python
Ruff is a Python linter, and Tomli is a package for working with toml files.
- [Ruff](https://github.com/charliermarsh/ruff)
- [Tomli](https://github.com/hukkin/tomli)

fix: Add "Ruff" and "Tomli" to Python dictionary

---

dictionaries/elixir/dict/elixir.txt
dictionaries/elixir/src/elixir.txt

shortdoc is how you add docs to Mix tasks in Elixir
https://hexdocs.pm/mix/1.14/Mix.Task.html

Add shortdoc to elixir.txt

---

dictionaries/css/src/css.txt

Basically #416, but ported to the CSS dictionary.
Dictionary: css
Add missing truetype & opentype - basically #416 but ported to the CSS dictionary
- issue 416

Add missing truetype & opentype

---

dictionaries/software-terms/src/software-terms.txt

Dictionary: `npmrc/benchmarker`
`npmrc`: It is the configuration file for npm.
`benchmarker`: Refers to the benchmarking tool.
- none

fix: Add `benchmarker` to software-terms.txt

---

README.md

add avatar of Contributors on README.md
I think this's an honor for the contributor
As shown

add avatar of Contributors on README.md

---

dictionaries/software-terms/src/software-tools.txt

[Ariakit](https://ariakit.org/) is an open source library of accessible React components and hooks.

fix: Add "ariakit" to the software tools dict

---

dictionaries/data-science/src/data-science-tools.txt
dictionaries/software-terms/src/software-tools.txt

Dictionary: software-tools.txt
add seaborn Ethr cygwin psping sockperf to software-tools.txt
detail info
modified:   dictionaries/software-terms/src/software-tools.txt
seaborn  https://seaborn.pydata.org/
Ethr     https://github.com/microsoft/ethr
cygwin   https://www.cygwin.com/
psping   https://learn.microsoft.com/en-us/sysinternals/downloads/psping
sockperf https://github.com/Mellanox/sockperf 

fix: add seaborn Ethr cygwin psping sockperf to software-tools.txt

---

README.md

Change Norwegian Bokmål link in README from `no_NB` to `nb_NO`

fix: Fix Norwegian Bokmål link in README

---

dictionaries/python/src/common_packages.txt

Dictionary: common_packages.txt
add words to common_packages.txt
detail add 
matplotlib.pyplot
torch.dequantize
optim.Adadelta
picklable
slurm
sigterm
Scapy
matplotlib.pyplot: is a library used for creating graphical interfaces, providing multiple methods for creating plots, scatter plots, histograms, etc.
torch.dequantize: is a library used for restoring quantized data to its original form, offering efficient quantization data restoration algorithms.
optim.Adadelta: is a library used for optimizing neural network parameters, employing adaptive learning rate algorithms.
picklable: is a library used forSerializing Python objects to byte streams, widely used in scientific computing and data exchange.
slurm: is a library used for distributed computing, providing tools for running computing …

fix: add words to common_packages

---

dictionaries/npm/src/npm.txt

Dictionary: npm.txt
add linkcss to npm.txt
LinkCSS: LinkCSS is a responsive and functional CSS framework that uses Web Components and Shadow DOM technology to make it easier for developers to build complex web applications. LinkCSS also originates from an open-source project on GitHub, created and maintained by developer Zhao Wanghu. The project's address is: https://github.com/linkcss/linkcss.

fix: add  linkcss to npm.txt

---

dictionaries/eo/package.json
dictionaries/eo/samples/seattle.md

Dictionary: `eo`
EO Dictionary was broken during the release process.
- `feat!:` - for breaking changes, like file format changes.

fix: Fix EO build issue.

---

package.json

Trying to find the version of `pnpm` that breaks the build.

chore: Update pnpm to 8.5.1

---

dictionaries/php/src/allowed-terms.txt

Dictionary: PHP
Added two wards in PHP dictionary
- [Laravel, a PHP framework](https://laravel.com/)
- [Laragon, a PHP stack local environment management](https://laragon.org/)

Added two words in php, Laravel & Laragon

---

dictionaries/css/src/css.txt

Dictionary: css
Add the new `srgb` value
- [color-mix()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix)

fix: Add `srgb` to css

---

dictionaries/en_shared/src/shared-additional-words.txt

Closes #2430
Crafter is a word but not yet recognized as one by spell.
- https://scrabble.merriam.com/finder/crafter
- https://en.m.wiktionary.org/wiki/crafter
- https://dictionary.cambridge.org/us/dictionary/english/crafter

fix: add "crafter" to en_shared

---

generator-cspell-dicts/generators/app/index.js

Dictionary: NA
Add definition to trie. 
Closes #2386 
NA

chore: Add definition to Trie in create-dictionary

---

dictionaries/python/src/common_packages.txt

"hhatto" owns the popular autopep8 repository.
https://github.com/hhatto/autopep8

fix: Add "hhatto" to Python dictionary

---

dictionaries/software-terms/src/software-tools.txt

Dictionary: software-tools.txt
add some linux display manager to software-tools.txt
| term     | reference.                             |
|----------|----------------------------------------|
| xfce     | https://xfce.org/                      |
| lightdm  | https://github.com/canonical/lightdm   |
| sddm     | https://github.com/sddm/sddm           |
| lxdm     | https://wiki.archlinux.org/title/LXDM  |
| xfwm     | https://wiki.archlinux.org/title/Xfwm  |
| lxqt     | https://lxqt-project.org/              |
| xinit    | https://wiki.archlinux.org/title/Xinit |
- `feat:` - for a significant change like adding a whole …

fix: add some linux display manager to software-tools.txt

---

dictionaries/php/src/php.txt

Dictionary: php
Add `3rd party vendors and packages` section, moved some vendor and package names there, added some terms.
Added terms:
- [FQCN](https://www.php.net/manual/en/language.namespaces.rules.php) (Fully Qualified Class Name);
- [pcov](https://pecl.php.net/package/pcov)
- [phpmd](https://phpmd.org/);
- [phpstan](https://phpstan.org/);
- [phpunit](https://phpunit.de/);
- [psalm](https://psalm.dev/);
- [PSR](https://www.php-fig.org/psr/);
- [Stringable](https://www.php.net/manual/en/class.stringable.php).
- `feat!:` - for …

fix: Add some language terms for the "php" dict

---

dictionaries/software-terms/src/software-tools.txt

[Gitleaks](https://github.com/gitleaks/gitleaks) is a tool for detecting and preventing hardcoded secrets.
Dictionary: software-tools
Add "Gitleaks"
[Gitleaks website](https://gitleaks.io/)

fix: Add "Gitleaks" to software tools dict

---

dictionaries/software-terms/src/software-terms.txt

Add "regexes."
- https://en.wikipedia.org/wiki/Regular_expression

fix: Add "regexes" to software-terms dictionary

---

dictionaries/software-terms/src/software-tools.txt

Add OpenAPI
[https://en.wikipedia.org/wiki/OpenAPI_Specification](https://en.wikipedia.org/wiki/OpenAPI_Specification)

fix: Add OpenAPI to software terms

---

dictionaries/software-terms/src/software-terms.txt

Add **_signin_** and **_signout_**
Often these are used with things like routes: `/signin` and `/signout`

Fix: Add signin and signout to software terms

---

dictionaries/software-terms/src/software-terms.txt

add `sqlserver` to software terms

fix: add sqlserver to software terms

---

dictionaries/software-terms/src/software-tools.txt

fix: add MSSQL to software tools

---

dictionaries/css/src/css.txt

fix: add viewports (plural) to css dictionary

---

dictionaries/en_US/src/en_US.txt

Dictionary: en-US
Not sure how it got there.
fixes #2535
- [indispensible or indispensable](https://www.google.com/search?q=indispensible+or+indispensable)

fix: Remove `indispensible`

---

dictionaries/shell/src/command-words.txt

[https://neovim.io/](https://neovim.io/)

fix: add neovim to shell words

---

dictionaries/software-terms/cspell-ext.json
dictionaries/software-terms/src/software-services.txt

Dictionary: `web-services`
Turn it on by default since some services are becoming popular and should not be added to the companies list.

feat: Enable dictionary `web-services` by default

---

dictionaries/css/src/css.txt

https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
- c2sc (small capitals from capitals)
- calt (contextual alternates)
- case (case-sensitive forms)
- dlig (discretionary ligatures)
- fina (final forms)
- frac (fractions)
- hist (historical forms)
- hlig (historical ligatures)
- init (initial forms)
- isol (isolated forms)
- kern (kerning)
- liga (standard ligatures)
- lnum (lining figures)
- locl (localized forms)
- medi (medial forms)
- mkmk (mark-to-mark positioning)
- onum (old style figures)
- rlig (required ligatures)
- smcp (small caps)
- subs (subscript)
- sups (superscript)
- swsh (swashes)
- tnum (tabular figures)
- zero (slashed zero)

fix: add font feature words to css

---

dictionaries/software-terms/src/software-tools.txt

Add "proselint" and "proselintrc." Proselint is a linter that uses a `.proselintrc` config file.
- [Proselint](https://github.com/amperser/proselint)

fix: Add "proselint" and "proselintrc" to software-terms dictionary

---

dictionaries/software-terms/src/software-terms.txt

fix: add jsonapi to software terms

---

dictionaries/software-terms/src/software-terms.txt

used with tools like `find`
https://man7.org/linux/man-pages/man1/find.1.html

fix: add mindepth and maxdepth to software terms

---

dictionaries/et-EE/LICENSE
dictionaries/et-EE/README.md
dictionaries/et-EE/package.json

Dictionary: et-EE
Convert et-EE license to LGPL 3.0
The et-EE dictionary used is the one found at [this link](http://www.meso.ee/~jjpp/speller/).  That dictionary is released with the following license statement (translated to English via Google Translate):
"The dictionary files on this page themselves are distributed under the GNU Lesser General Public License"

feat!: Convert et-EE license to LGPL 3.0

---

dictionaries/cs_CZ/README.md
dictionaries/de_DE/README.md
dictionaries/en_AU/README.md
dictionaries/en_CA/README.md
dictionaries/en_GB-MIT/README.md
dictionaries/en_GB/README.md
dictionaries/en_US/README.md
dictionaries/es_ES/README.md
dictionaries/nl_NL/README.md
dictionaries/pl_PL/README.md
dictionaries/pt_BR/README.md
dictionaries/pt_PT/README.md
dictionaries/ru_RU/README.md
dictionaries/sk_SK/README.md
dictionaries/sl_SI/README.md

Dictionaries (update license info): de_DE, es_ES, pl_PL
In each of these dictionaries, there are the following: 
1) a LICENSE file
2) a license listed in package.json
3) a license referenced in the README.
In these three dictionaries, (1) and (2) match, but (3) did not, and instead said `MIT`.  This PR does not change the license the dictionaries are released under, but does fix the documentation in the READMEs so that (3) matches (1) and (2).
n/a
Additionally, this changes some relative links to hard-coded URLs, so that they will work in their NPM packages:
Dictionaries (update links): cs_CZ, de_DE, en_AU, en_CA, en_GB, en_GB-MIT, en_US, es_ES, nl_NL, pl_PL, pt_BR, pt_PT, ru_RU, sk_SK, sl_SI …

fix: Make license documentation consistent

---

dictionaries/software-terms/src/software-terms.txt

- [themeable - Wiktionary, the free dictionary](https://en.wiktionary.org/wiki/themeable)
- [ThemeableAttribute.Themeable Property (System.Web.UI) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.web.ui.themeableattribute.themeable?view=netframework-4.8.1)

fix: Add `themeable` to software terms

---

dictionaries/en_US/src/hunspell/en_US-large.dic
dictionaries/en_shared/src/shared-additional-words.txt

Dictionary: _en_US_
_Add "archivable" to en_US_
- [_Merriam-Webster_](https://www.merriam-webster.com/dictionary/archivable)

fix: Add "archivable" to English dictionaries

---

dictionaries/fsharp/dict/fsharp.txt
dictionaries/fsharp/src/from-fsharp-src.txt

name: Remove typo from fsharp
about: PR for typo from fsharp dictionary
title: 'fix: '
labels: dictionary
Dictionary: fsharp
Remove typo 
https://github.com/streetsidesoftware/cspell-dicts/blob/2115190bae015aedb8832bc8384088ed36cfce9a/dictionaries/en-common-misspellings/dict-en.yaml#L2561

fix: remove typo from fsharp dictionary

---

dictionaries/kotlin/package.json
dictionaries/makefile/package.json
dictionaries/vim/package.json
generator-cspell-dicts/generators/app/run.js
generator-cspell-dicts/generators/app/templates/package.json
generator-cspell-dicts/package.json
generator-cspell-dicts/run.js
package.json
pnpm-lock.yaml

The `yo` package is very old and cannot use the new `yoeman-generator`.

chore: Use custom runner for generator

---

dictionaries/filetypes/filetypes.txt

Dictionary: _filetypes_
Adds
- pem
- crx
- puml
- drawio
- https://stackoverflow.com/questions/50615890/what-is-the-chrome-extension-pem-file-for
- https://plantuml.com/sources
- https://www.drawio.com/doc/faq/save-file-formats#:~:text=.drawio%20(XML%20file)%3A%20this,with%20our%20file%20extension%20name.

fix: Add several filetypes

---

dictionaries/python/src/python/python.txt

Add "PYTHONHOME" to the python dictionary.
[Python documentation](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME) of the PYTHONHOME environment variable

fix: Add "PYTHONHOME" to python dict

---

dictionaries/fa_IR/LICENSE
dictionaries/fa_IR/README.md
dictionaries/fa_IR/package.json
dictionaries/he/LICENSE
dictionaries/he/README.md
dictionaries/he/package.json
dictionaries/lt_LT/LICENSE
dictionaries/lt_LT/README.md
dictionaries/lt_LT/package.json
dictionaries/ro_RO/LICENSE
dictionaries/ro_RO/README.md
dictionaries/ro_RO/package.json
dictionaries/uk_UA/LICENSE
dictionaries/uk_UA/README.md
dictionaries/uk_UA/package.json

Dictionaries: en-common-misspellings, fa_IR, he, lt_LT, ro_RO, uk_UA
Related to #441 
Made the following license changes:
- ~`en-common-misspellings`: `MIT` -> `CC BY-SA 4.0`~
EDIT: Moved to separate branch
- `fa_IR`: `MIT` -> `Apache 2.0`
- `he`: `MIT` -> `AGPLv2`
- `lt_LT`: `MIT` -> `BSD-3-clause`
- `ro_RO`: `LGPL` -> `GPL-3.0`
- `uk_UA`: `LGPL` -> `GPL-3.0`
Dictionary link | cspell documentation of source | Dictionary Source link
-- | -- | --
fa_IR | https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/fa_IR | https://github.com/b00f/lilak
he | https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/he |  http://hspell.ivrix.org.il/
lt_LT | https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/lt_LT | …

feat!: Update licenses for several dictionaries to match license of their sources

---

dictionaries/vim/src/vim.txt

add `isempty` to vim dictionary

fix: add isempty to vim dict

---

dictionaries/bash/src/bash-words.txt

Per https://man7.org/linux/man-pages/man1/getopts.1p.html
Dictionary: bash
- Add OPTARG to bash-words.txt
- https://man7.org/linux/man-pages/man1/getopts.1p.html

fix: Add OPTARG to bash-words.txt

---

dictionaries/npm/src/npm.txt

Add "npmcli," "npm-package-json-lint," "npmpackagejsonlint," "npmpackagejsonlintignore," and "npmpacakgejsonlintrc" to npm dictionary.
- https://www.npmjs.com/package/@npmcli/fs
- https://npmpackagejsonlint.org/docs/configuration
- https://npmpackagejsonlint.org/docs/ignore

fix: Add some npmcli and npm-package-json-lint terms

---

dictionaries/software-terms/src/software-terms.txt

Add the term "datasources," which is used in Renovate's config files, for example.
- https://docs.renovatebot.com/modules/datasource/

fix: Add "datasources" to software-terms dict

---

dictionaries/software-terms/src/software-tools.txt

Add "gitleaksignore," "SlackAPI," "Trivy," and "trivyignore."
- [gitleaksignore](https://github.com/gitleaks/gitleaks/blob/8de8938ad425d11edb0986c38890116525a36035/README.md#gitleaksignore)
- [SlackAPI](https://github.com/slackapi/)
- [Trivy](https://aquasecurity.github.io/trivy/)
- [trivyignore](https://aquasecurity.github.io/trivy/v0.48/docs/configuration/filtering/#trivyignore)

fix: Add some Gitleaks, Slack API, and Trivy terms

---

dictionaries/git/cspell-ext.json
dictionaries/git/cspell.json

Dictionary: git
Add "autocrlf" term
- [autocrlf](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf).

feat!: [git] Add a "git" dictionary to hold git related terms.

---

dictionaries/rust/src/rust.txt

Dictionary: Rust
Apologies for the PR spam, I'm opening these as I run into issues as they should be quick to review.
This PR fixes a spelling mistake where what I expect was "BitAnd" got changed into "BitAdd". The "BitAdd" operator doesn't really make sense to me plus I can't find any references to one on google so I've just replaced it.
- https://doc.rust-lang.org/std/ops/trait.BitAnd.html

fix: correct "BitAdd" to "BitAnd" in rust dictionary

---

dictionaries/rust/src/rust.txt

This PR adds the acronym "msrv" (Minimum supported rust version) to the Rust dictionary.
- Usage of MSRV is shown here: https://rust-lang.github.io/rfcs/2495-min-rust-version.html

fix: add "msrv" to rust dictionary

---

dictionaries/rust/src/rust.txt

Dictionary: [Rust](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/rust)
This PR adds "rustfmt" to the Rust dictionary as it's a common tool used in rust projects.
- https://github.com/rust-lang/rustfmt

fix: add `rustfmt` to rust dictionary

---

dictionaries/gaming-terms/src/gaming-terms.txt

Dictionary: gaming-terms
Add the term "despawn". It is used in gaming and game development.
[Wikipedia](https://en.wikipedia.org/wiki/Spawning_(video_games))

fix: add Despawn to gaming-terms dictionary

---

dictionaries/cpp/src/cpp.txt

Dictionary: cpp
fixes [#2967](https://github.com/streetsidesoftware/cspell-dicts/issues/2967)

fix: Fix spelling of subsytem in CPP word list (to subsystem)

---

dictionaries/software-terms/src/software-terms.txt

fixes #2977 
Add word typeahead
- https://en.wikipedia.org/wiki/Typeahead

fix: add typeahead to software terms

---

dictionaries/julia/cspell-ext.json
dictionaries/julia/cspell.json
dictionaries/julia/package.json
dictionaries/julia/samples/code.jl

Dictionary: _julia_
- Add sample code for tests

chore: Add Julia sample code

---

dictionaries/julia/package.json

Dictionary: _julia_
Make it public so it is published.

fix: Publish Julia dictionary

---

dictionaries/monkeyc/cspell-ext.json
dictionaries/monkeyc/cspell.json

Dictionary: _monkeyc_
Dictionaries should not add to the global `words`.

fix: Do not add to "words"

---

dictionaries/software-terms/src/software-terms.txt

Adds kanban to the software terms dictionary (e.g., https://en.wikipedia.org/wiki/Kanban_board)
- https://en.wikipedia.org/wiki/Kanban_board

fix: add "kanban" to software terms

---

dictionaries/en_US/src/en_US.txt

Dictionary: _en_US_
fixes #3111
- [persistance - Did you spell it correctly. Alternative spellings in the British English Dictionary - Cambridge Dictionary](https://dictionary.cambridge.org/spellcheck/english/?q=persistance)

fix: Remove `persistance` from en_US

---

dictionaries/rust/src/rust.txt

Dictionary: [Rust](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/rust)
This PR adds "powf" and "powi" to the Rust dictionary as they are used for exponentiation for floats.
- https://doc.rust-lang.org/std/primitive.f32.html#method.powf
- https://doc.rust-lang.org/std/primitive.f64.html#method.powi

fix: add `powf` and `powi` to rust dictionary

---

dictionaries/uk_UA/cspell-ext.json

Dictionary: uk-ua
Replace ʼ to ' for uk dictionary lookups.
Based on https://github.com/brown-uk/dict_uk/issues/317

fix: add uk dictionary replacement map (`ʼ` -> `'`)

---

dictionaries/fullstack/cspell-ext.json
dictionaries/markdown/cspell-ext.json
dictionaries/typescript/cspell-ext.json

- Enable dictionaries for MDX.
MDX is Markdown + JavaScript React - the respective settings should be enabled.

fix: Enable dictionaries for MDX

---

dictionaries/software-terms/src/software-terms.txt

Dictionary: en_GB and en_US
The word Lexer is commonly used in programming, but wasn't in the dictionaries.
- None

fix: add Lexer to Software Terms dictionaries

---

dictionaries/people-names/CHANGELOG.md
dictionaries/people-names/LICENSE
dictionaries/people-names/README.md
dictionaries/people-names/checksum.txt
dictionaries/people-names/cspell-ext.json
dictionaries/people-names/cspell-tools.config.yaml
dictionaries/people-names/cspell.json
dictionaries/people-names/dict/README.md
dictionaries/people-names/dict/people-names.txt
dictionaries/people-names/package.json
dictionaries/people-names/src/README.md
dictionaries/people-names/src/names.txt
pnpm-lock.yaml

feat: Add People Names dictionary.

---

dictionaries/rust/src/rust.txt
dictionaries/software-terms/src/software-terms.txt

Dictionary: rust
I noticed that the name of the popular crate `tokio` was missing.
- None

fix: Add tokio

---

dictionaries/en-common-misspellings/dict-en.yaml
dictionaries/en_AU/cspell-tools.config.yaml
dictionaries/en_CA/cspell-tools.config.yaml
dictionaries/en_GB-MIT/cspell-tools.config.yaml
dictionaries/en_GB/cspell-tools.config.yaml
dictionaries/en_GB/src/exclude-words.txt
dictionaries/en_US/cspell-tools.config.yaml
dictionaries/en_US/src/en_US.txt
dictionaries/en_shared/cspell-tools.config.yaml
dictionaries/en_shared/src/exclude-words.txt
package.json
pnpm-lock.yaml

Dictionary: English
Remove lower case `colum` from the English dictionaries and add a suggestion: `colum->column`.
Related to #3311 
This PR also sets up a common `exclude-words.txt` file to remove words from the English dictionaries.

fix: Remove lower case `colum` from English dictionaries.

---

dictionaries/people-names/checksum.txt
dictionaries/people-names/cspell-tools.config.yaml
dictionaries/people-names/dict/people-names.txt
dictionaries/people-names/package.json

Dictionary: _people-names_
This change enforces the correct capitalization of names when spell checking.

fix: prevent lower case versions of names.

---

dictionaries/companies/src/companies.txt

Dictionary: `companies`
ADI is the commonly used acronym by Analog Devices employees themselves (hi 👋), it's also all over https://www.analog.com/ and it's the company's stock ticker.
- https://en.wikipedia.org/wiki/Analog_Devices

fix: add missing company acronym for Analog Devices

---

dictionaries/software-terms/src/software-terms.txt

Dictionary: `softwareTerms`
This adds the counterpart to `sort`, since we already have `sorted`/`unsorted`, etc.
- This is defined as a computing term in https://en.wiktionary.org/wiki/unsort:
> To shuffle a data structure so that it is no longer sorted.

fix: add unsort to the list of software terms

---

dictionaries/software-terms/src/coding-terms.txt

- Add redetect, backport, and different valid forms of them.
- Add preinstalled (past tense of preinstall already in git)
- [wikipedia.org/wiki/Backporting](https://en.wikipedia.org/wiki/Backporting)
- [merriam-webster.com/dictionary/preinstall](https://www.merriam-webster.com/dictionary/preinstall)
- [wiktionary.org/wiki/redetect](https://en.wiktionary.org/wiki/redetect), <https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/ff799054(v=ws.11)>
- [docs.python.org/3/library/traceback.html](https://docs.python.org/3/library/traceback.html)
- `feat!:` - …

Update coding-terms.txt (resolves #3472).

---

dictionaries/aws/src/aws.txt
dictionaries/bash/src/bash-words.txt
dictionaries/terraform/src/terraform.txt

Dictionary: aws, bash, terraform
Added words that were found by CSpell in my project. I have added references to the words below. 
- aws
- [ipam](https://docs.aws.amazon.com/vpc/latest/ipam/what-it-is-ipam.html)
- [gwlb](https://aws.amazon.com/blogs/aws/introducing-aws-gateway-load-balancer-easy-deployment-scalability-and-high-availability-for-partner-appliances/)
- [ecmp](https://aws.amazon.com/blogs/networking-and-content-delivery/scaling-vpn-throughput-using-aws-transit-gateway/)
- [tiros](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awstiros.html)
- [dopt](https://docs.aws.amazon.com/directoryservice/latest/admin-guide/dhcp_options_set.html)
- [wafv](https://aws.amazon.com/waf/)
- [amazonmq](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-r …

fix: update to aws, bash, and terraform dictionaries

---

dictionaries/powershell/src/powershell.txt

Fix PowerShell dict
Resolves #3540 
Add `runspace` and `runspaces` to PowerShell dict

fix: PowerShell add Runspace(s)

---

dictionaries/powershell/src/powershell.txt

Dictionary: PowerShell
Adds `-isnot` to the PowerShell dictionary
- [https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.4#type-comparison](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.4#type-comparison)

fix: add `-isnot` to powershell dictionary fixes streetsidesoftware/cspell-dicts#3577

---

dictionaries/html/src/html.txt

Dictionary: HTML
Adds new Shadow Root related HTML attributes.
- There are [four new attributes](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element) for the `<template>` element. And the `shadowroot` has been renamed to `shadowrootmode`.

fix: Add new Shadow Root related HTML attributes

---

dictionaries/bash/dict/bash-words.txt
dictionaries/bash/src/bash-words.txt

Bash strict mode is a very popular command `set -euxo pipefail` which
generates a false positives with cspell.
See: http://redsymbol.net/articles/unofficial-bash-strict-mode/

fix: Recognize bash strict mode arguments

---

dictionaries/software-terms/src/coding-terms.txt

This is (too) commonly used when testing software, such as [here](https://testing-library.com/docs/queries/bytestid/). This is often used in the context of a HTML data attribute, e.g. `data-testid="foo"` which CSpell flags as an error.
I followed the advice listed at https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/software-terms.txt#L5, let me know if you'd prefer me to add this to a different file.

fix: add testid to the list of coding terms

---

dictionaries/software-terms/src/coding-terms.txt

commonly used for structuring code in blocks with #region ... #endregion
endregion was picked up as false positive

fix: add endregion

---

dictionaries/software-terms/src/software-tools.txt

This adds `all-contributorsrc` which is the name of the config file used by the All Contributors CLI/GitHub bot.
- https://allcontributors.org/docs/en/bot/configuration

fix: add all-contributorsrc to software-tools.txt

---

dictionaries/bash/src/bash-words.txt
dictionaries/shell/src/shell-zsh-words.txt

Dictionary: bash
This adds `zdotdir` to the bash dictionary, which is a variable used by zsh.
- https://zsh.sourceforge.io/Guide/zshguide02.html

fix: add zdotdir to shell dictionary

---

dictionaries/docker/src/docker-words.txt

Dictionary: docker
This adds `hadolint` to the docker dictionary, which is a popular Dockerfile linter.
- [_Any source references._](https://github.com/hadolint/hadolint)

fix: add hadolint to docker dictionary

---

dictionaries/software-terms/src/coding-terms.txt

This adds the term `azdo`, which is a common abbreviation for Azure DevOps. Thanks!
- https://learn.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops#prerequisites

fix: add azdo to coding-terms.txt

---

dictionaries/python/dict/python.txt
dictionaries/python/src/python/python.txt

Dictionary: python.txt
The `split` method in the `re` package has a keyword argument `maxsplit`.
https://docs.python.org/3/library/re.html#re.split

fix: Add "maxsplit" to python.txt dictionary

---

dictionaries/filetypes/src/filetypes.txt
dictionaries/typescript/cspell-ext.json
dictionaries/typescript/dict/typescript.txt
dictionaries/typescript/samples/asmple.astro
dictionaries/typescript/src/ecosystem-terms.txt

Dictionary: _typescript_
fixes #3712

fix: Add Astro to TypeScript dictionary settings

---

dictionaries/terraform/src/terraform.txt

Available in [version 0.14](https://developer.hashicorp.com/terraform/language/functions/alltrue)
Dictionary: terraform
add alltrue
Available in [version 0.14](https://developer.hashicorp.com/terraform/language/functions/alltrue)

fix(terraform): add alltrue to allowed words

---

dictionaries/npm/src/npm.txt

TSTyche is a big fan of CSpell. I am using the spell checker from the first days of [the repo](https://github.com/tstyche/tstyche). Would it be possible to include it in the npm dictionary?
Package page: https://www.npmjs.com/package/tstyche

fix: add `tstyche` to npm dictionary

---

dictionaries/npm/src/npm.txt

Thanks for adding `tstyche` to the npm dictionary. Would it be possible to add few more npm package names? These are used for TSTyche website (;
fontsource: https://www.npmjs.com/package/@fontsource/roboto (and many other fonts)
nextra: https://www.npmjs.com/package/nextra
tailwindcss: https://www.npmjs.com/package/tailwindcss (very popular!)

fix: add few more npm package names

---

dictionaries/filetypes/src/filetypes.txt

Dictionary: filetypes
lockb is the file extension for Bun's lock file.
Bun is a popular package manager for JavaScript/TypeScript.
https://bun.sh/docs/install/lockfile

fix: add lockb to filetypes

---

CONTRIBUTING.md

Copies the intent from https://github.com/streetsidesoftware/cspell-dicts/issues/3866#issuecomment-2538251022 into docs.
https://github.com/streetsidesoftware/cspell-dicts/issues/3866#issuecomment-2538251022
I would have used `docs:` as the prefix, but it's not on the checklist.

chore: add docs on proposing words

---

dictionaries/companies/src/companies.txt
dictionaries/gaming-terms/src/gaming-terms.txt
dictionaries/software-terms/src/coding-terms.txt
dictionaries/software-terms/src/software-terms.txt

Dictionary: _coding-terms_, _software-terms_
Adds the following terms:
* `coding-terms`:
* `automerge`
* `outro`
* `tada`
* `wontfix`
* `software-terms`
* `konami`
* `konami`: https://en.wikipedia.org/wiki/Konami_Code
* `outro`: https://en.wiktionary.org/wiki/outro
* `tada`: https://en.wikipedia.org/wiki/Party_popper#:~:text=tada
For `automerge` and `wontfix`, I don't have specific references to share, but they're pretty common slang that I've used. Is that acceptable? 🙂 

fix: add a few coding and software terms

---

dictionaries/npm/src/npm-keywords.txt

- `preid`: Command `npm version` has an prerelease identifier option `--preid` to use as a prefix for the "prerelease" part of a SemVer.
Like the `alpha` in `1.0.0-alpha.1`.
Add `preid` word for option `--preid` from `npm version` command.
[NPM documentation about `preid`](https://docs.npmjs.com/cli/v8/commands/npm-version#preid)

fix: Add word preid to npm dictionary

---

dictionaries/companies/src/companies.txt

Dictionary: _companies_
Adds Bluesky and Emojipedia to the list.
* https://bsky.app
* https://emojipedia.org

fix: add Bluesky and Emojipedia to companies dictionary

---

dictionaries/companies/src/companies.txt
dictionaries/software-terms/src/software-terms.txt
dictionaries/software-terms/src/software-tools.txt

Add a few new terms and remove a duplicate LinkedIn entry
Dictionary:
- software-tools.txt
- software-terms.txt
- companies.txt
- Remove duplicate LinkedIn companies.txt entry
- Add Chocolatey to companies.txt (https://chocolatey.org/)
- Add AICPA to companies.txt (https://www.aicpa-cima.com)
- Add Pentoo to software-tools.txt (https://www.pentoo.ch/)
- Add ptrace to software-tools.txt (https://man7.org/linux/man-pages/man2/ptrace.2.html)
- Add runc to software-tools.txt (https://github.com/opencontainers/runc)
- Add Altri to companies.txt (https://altri.pt)
- Add ASLR to software-terms.txt (https://en.wikipedia.org/wiki/Address_space_layout_randomization)
- `feat:` - for a significant …

fix: Add missing companies + software tool terms

---

dictionaries/city-names-finland/cspell-ext.json
dictionaries/people-names/cspell-ext.json

Dictionaries that are enabled in `languageSettings` are harder to disable than the ones enabled in the root `dictionaries`.

fix: make it easier to turn off dictionary

---

.github/actions/quick-setup/action.yaml
.github/actions/setup/action.yaml
.github/workflows/test.yml

- Use Node 22.x as the default instead of Node 18.x.
- Use Node 22.x when testing Windows.

chore: default to node 22

---

dictionaries/ada/cspell.json
dictionaries/al/cspell-ext.json
dictionaries/dart/cspell-ext.json
dictionaries/elisp/cspell.json
dictionaries/flutter/cspell-ext.json
dictionaries/fsharp/cspell-ext.json
dictionaries/julia/cspell-ext.json
dictionaries/kotlin/cspell-ext.json
dictionaries/r/cspell-ext.json
dictionaries/sql/cspell-ext.json
dictionaries/terraform/cspell-ext.json
dictionaries/typescript/cspell-ext.json

Dictionary: `ada`, `al`, `astro`, `dart`, `elisp`, `lisp`, `fsharp`, `julia`, `kotlin`, `r`, `sql` and `terraform`
Removing `enableFiletypes` from all the dictionary extensions. It is creating confusion.
This is related to: [enabledFileTypes "*": false does not function correctly](https://github.com/streetsidesoftware/vscode-spell-checker/issues/3836#issuecomment-2577830227)

feat: remove `enableFiletypes`

---

dictionaries/fullstack/src/fullstack.txt

Add `nodenext` to the `fullstack` dictionary.
Not sure if the `fullstack` dictionary is the best place to add `nodenext`. The dictionary already has `esnext`, so perhaps `nodenext` could also live here too. Or?
`nodenext` can be set as a value of [`module`](https://www.typescriptlang.org/tsconfig/#module) or [`moduleResolution`](https://www.typescriptlang.org/tsconfig/#moduleResolution) options of TSConfig file. (Very similarly `esnext` can be set as a value of `module` or `target` options.)
Currently `cspell` does not allow to use `nodenext` in a TSConfig file or code base.
- `feat!:` - for breaking …

fix: add `nodenext`

---

dictionaries/terraform/cspell-ext.json

Dictionary: terraform
The default file type of a terraform `.tf` file reported by VS Code is `tf`, not `terraform`.
This change makes sure that the dictionary will be used in that case.
fixes: https://github.com/streetsidesoftware/vscode-spell-checker/issues/4166

fix: Make sure files of type `tf` use `terraform` dict

---

dictionaries/software-terms/src/coding-terms.txt

Added some Samba-related words.
- [browseable](https://www.samba.org/samba/docs/4.9/man-html/smb.conf.5.html)
- [samba](https://www.samba.org/)
- [smbclient](https://www.samba.org/samba/docs/4.9/man-html/smbclient.1.html)
- [smbd](https://www.samba.org/samba/docs/4.17/man-html/smbd.8.html)
- [smbpasswd](https://www.samba.org/samba/docs/4.9/man-html/smbpasswd.8.html)

fix: Add Samba-related words

---

dictionaries/software-terms/src/coding-terms.txt

Sorry, I made a typo in https://github.com/streetsidesoftware/cspell-dicts/pull/4159.
- [indentless_arrays](https://github.com/google/yamlfmt/blob/928ce33e9afa338486d889549fc78e6b7feabeaf/docs/config-file.md)

fix: Fix typo of indentless_arrays

---

dictionaries/en_shared/src/shared-additional-words.txt

Add "succumber" to the en_shared dictionary to complement the existing "succumbence" and "succumbency" words.
- Dictionary.com lists "succumber" as a derived form of "succumb": https://www.dictionary.com/browse/succumb

fix: Add "succumber", "succumbence", and "succumbency" to the en_shared dictionary to complement the existing.

---

dictionaries/node/src/node.txt
dictionaries/npm/src/npm.txt
dictionaries/software-terms/src/software-tools.txt

Dictionary: _node_, _npm_, _software-tools_
Adds:
* `attw`: the bin commanded set by https://www.npmjs.com/package/@arethetypeswrong/cli
* `markdownlintignore`: the standard ignore file for https://github.com/igorshubovych/markdownlint-cli
* `npmjs`: the website used for npm
* https://www.npmjs.com/package/@arethetypeswrong/cli
* https://github.com/igorshubovych/markdownlint-cli
* https://npmjs.com

fix: add attw, markdownlintignore, npmjs words

---

dictionaries/gaming-terms/src/gaming-terms.txt
dictionaries/software-terms/src/coding-terms.txt

Dictionary: _coding terms_, _gaming terms_
Adds "boop". 
From https://en.wiktionary.org/wiki/boop:
> 1. A low-pitched beeping sound.
> (colloquial) 2. A gentle or playful tap or strike, especially on the nose.
1. _"Beep boop"_ is a phrase sometimes used to refer to computer noises
2. _"Boop"_ on its own is also used to refer to _"booping"_ something
Also, Jake from Adventure Time: https://www.youtube.com/watch?v=X6SX50H54Gg
- `chore:` - for changes that do not im

fix: add 'boop'

---

dictionaries/cpp/dict/cpp.txt
dictionaries/cpp/samples/cpp.txt
dictionaries/cpp/src/cpp.txt
dictionaries/cpp/src/exclude-terms.txt

Dictionary: CPP
Remove misspelling `equivelent ` from CPP
fixes #4225 

fix: Remove misspelling `equivelent ` from CPP

---

dictionaries/npm/src/npm.txt

This is adding [`neostandard`](https://www.npmjs.com/package/neostandard).
https://www.npmjs.com/package/neostandard

fix: add `neostandard`

---

dictionaries/typescript/cspell-ext.json
dictionaries/typescript/samples/sample.tsx

Dictionary: TypeScript / JavaScript
Ignore BitInt literal hex numbers.
Fixes #4237 
- [BigInt - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)

fix: Ignore BitInt literal hex numbers.

---

dictionaries/software-terms/src/software-terms.txt

Adds a single word to software terms, this word is also defined on Collins (British dictionary)!
- decompile
- [decompile on Collins, a British Dictionary](https://www.collinsdictionary.com/dictionary/english/decompile)
- [decompile on Wordnik, an open dictionary](https://www.wordnik.com/words/decompile)
- [decompiler on Wikipedia](https://en.wikipedia.org/wiki/Decompiler)

fix: add decompile to software terms

---

dictionaries/companies/src/companies.txt

Adds `Fonticons, Inc.`, the company behind Font Awesome.
> Fonticons, Inc., a Delaware corporation (the Company)…
> 
> — https://fontawesome.com/license
* https://github.com/svg/svgo/pull/2101

fix: add fonticons (fontawesome) to companies

---

dictionaries/en_shared/src/shared-additional-words.txt

Dictionary: shared-additional-words
Adds the word "Bézier" with the the diacritic. Merriam-Webster, an American English dictionary has an entry for this, but British Dictionaries don't seem to.
On Wikipedia, it is always referred to with the diacritic as well, despite the dictionary suggesting it's less common to do so.
- https://en.wikipedia.org/wiki/B%C3%A9zier_curve
- https://www.merriam-webster.com/dictionary/Bezier — See variants
* https://github.com/svg/svgo/pull/2101

fix: add bézier to dictionary

---

dictionaries/ca/cspell-ext.json
dictionaries/da_DK/cspell-ext.json
dictionaries/de_AT/cspell-ext.json
dictionaries/de_CH/cspell-ext.json
dictionaries/de_DE/cspell-ext.json
dictionaries/fr_FR/cspell-ext.json
dictionaries/fr_FR_90/cspell-ext.json
dictionaries/hr_HR/cspell-ext.json
dictionaries/hu_HU/cspell-ext.json
dictionaries/la/cspell-ext.json
dictionaries/mn_MN/cspell-ext.json
dictionaries/nl_NL/cspell-ext.json
dictionaries/pt_BR/cspell-ext.json
dictionaries/ru_RU/cspell-ext.json
dictionaries/sv/cspell-ext.json

Forbidden words in language dictionaries can cause problems when combined with other dictionaries.
For not, just treat forbidden words as not found in the dictionary.

feat: Ignore Forbidden Words

---

dictionaries/npm/dict/npm.txt
dictionaries/npm/src/npm.txt

Adds "tsdown"
- https://github.com/rolldown/tsdown

fix: add 'tsdown'

---

dictionaries/software-terms/src/software-terms.txt

Dictionary: software-terms.txt
Added `demosaic` and its different forms to software-terms.
This word is used in digital image processing.
- https://en.wikipedia.org/wiki/Demosaicing
- demosaic
- demosaiced
- demosaicing
- demosaics
- https://en.wiktionary.org/wiki/demosaics
- https://arxiv.org/abs/2211.13732

fix: add demosaic to software-terms

---

dictionaries/software-terms/src/coding-terms.txt

`autofix` and `autoupdate` are sometimes used instead of `auto-fix` or `auto-update`.
- https://pre-commit.ci/

fix: add pre-commit-related words to coding-terms

---

dictionaries/software-terms/src/coding-terms.txt

Added `decel` to coding-terms as the combination of accel/decel is frequently used in coding.
- https://docs.nav2.org/configuration/packages/configuring-velocity-smoother.html

fix: add decel to coding-terms

---

dictionaries/en_GB-MIT/cspell-ext.json
dictionaries/en_GB-MIT/cspell-tools.config.yaml

Dictionary: _en_GB-MIT_
Make sure the `en-gb-mit` dictionary is a drop in replacement for the LGPL `en-gb` dictionary.
By reusing the dictionary name, it allows for replacement.

fix: Make sure `en_GB-MIT` is a drop in replacement for `en_GB`.

---

dictionaries/aoo-mozilla-en-dict/README.md
dictionaries/en_AU/README.md
dictionaries/en_AU/cspell-tools.config.yaml
dictionaries/en_AU/src/README.md
dictionaries/en_AU/src/hunspell-en_AU-large/README.md
dictionaries/en_CA/README.md
dictionaries/en_CA/cspell-tools.config.yaml
dictionaries/en_CA/src/README.md
dictionaries/en_CA/src/hunspell-en_CA-large/README.md
dictionaries/en_GB-MIT/README.md
dictionaries/en_GB-MIT/cspell-tools.config.yaml
dictionaries/en_GB-MIT/src/README.md
dictionaries/en_GB-ise/README.md
dictionaries/en_GB-ise/cspell-tools.config.yaml
dictionaries/en_GB-ise/src/README.md
dictionaries/en_GB-legacy/cspell-tools.config.yaml
dictionaries/en_GB-legacy/src/README.md
dictionaries/en_GB/README.md
dictionaries/en_GB/cspell-tools.config.yaml
dictionaries/en_GB/src/README.md
dictionaries/en_US/README.md
dictionaries/en_US/src/README.md
dictionaries/en_US/src/hunspell/README.md
dictionaries/en_US/src/legacy/README.md
dictionaries/en_shared/cspell-tools.config.yaml
dictionaries/en_shared/src/README.md
dictionaries/en_shared/src/shared-additional-words-ise.txt
pnpm-lock.yaml

Dictionary: _all English dictionary`
- **chore: add instructions for external dictionaries source**
- **chore: add maintenance instructions for English dictionaries**
- **chore: add instructions for en_GB and en_GB-legacy**
- **chore: update contributions instructions in README files**
- **feat: add a shared-additional-words-ise.txt to en_shared**
- https://github.com/streetsidesoftware/cspell-dicts/pull/4391#discussion_r2072976066

refactor: consolidate English shared `-ise` words into `shared-additional-words-ise.txt`

---

dictionaries/en_AU/README.md
dictionaries/en_AU/src/LICENSE
dictionaries/en_CA/README.md
dictionaries/en_CA/src/LICENSE
dictionaries/en_GB-ise/README.md
dictionaries/en_GB-ise/src/LICENSE
dictionaries/en_GB/README.md
dictionaries/en_GB/src/LICENSE

- **fix: error in license for en_AU, en_CA & en_GB dictionaries**
The packages were provided under LGPL-3, not GPL3
- **chore: add a LICENSE file to some src directories**
We should make it clear that contributions to these dictionaries are under MIT license
- **chore: add more information to license in README files**
Explain the differences between the way the dictionaries are packaged and the license for the files in the repository.
Closes #4408
Closes #4409 
Closes #4410 
- #4408
- #4409 
- #4410
- `chore:` - for changes that …

chore: Adjust in license referenced in README to match LICENSE file in en_AU, en_CA & en_GB

---

dictionaries/software-terms/cspell-corrections.yaml

- feat: add variations of commit to software corrections
committer, committers, commitable, committing are very oftenly wrongly written by developpers.
feat: add variations of commit to software corrections
committer, committers, committable, committing are often wrongly written by developers.
Please note, I noticed some of these words are already in [en-common-misspellings](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/en-common-misspellings) dictionary, but this one is licensed with a restrictive license: CC BY-SA 4.0
It's better to have them in this dictionary that is licensed with MIT.
- `feat:` - for a significant change like …

fix: add variations of commit to software corrections

---

dictionaries/git/cspell-ext.json

Dictionary: _git_
Enabled the `git` dictionary when the file type is either git-commit -r commit-msg.
Related to #4451

fix: Enable git dictionary for commit-msg

---

dictionaries/software-terms/README.md
dictionaries/software-terms/cspell-tools.config.yaml
dictionaries/software-terms/src/README.md
dictionaries/software-terms/src/software-terms-legacy.txt
dictionaries/software-terms/src/software-terms.txt

The content of software-terms.txt comes from years of contributions.
It doesn't reflect the expected content of the software-terms dictionary.
This PR is about setting up the software-terms-legacy.txt file, and its addition to software-terms dictionary.
Other PRs will follow to move the outdated content from software-terms.txt to software-terms-legacy.txt
This PR replaces #4443
- https://github.com/streetsidesoftware/cspell-dicts/pull/4443

chore: add software-terms-legacy.txt

---

dictionaries/en-common-misspellings/src/LICENSE
dictionaries/en-common-misspellings/src/README.md
dictionaries/en-common-misspellings/src/additional-suggestions.txt

Dictionary: en-common-misspellings
Set up a src directory with an MIT license so we can use the suggestions in other places.

chore: Add src to en-common-misspellings

---

dictionaries/en_GB-MIT/cspell-tools.config.yaml

Dictionary: _en_GB-MIT_
Add en_shared -ize form to en_GB-MIT dictionary
This comment was left behind in a previous PR because it was resolved, but it was valuable.
> Yes, en_GB-MIT is good. Any shared additions should go there as long as they are under the MIT license.
> _Originally posted by @Jason3S in https://github.com/streetsidesoftware/cspell-dicts/pull/4438#discussion_r2108307413_

feat: add en_shared -ize forms to en_GB-MIT

---

dictionaries/en_shared/README.md
dictionaries/en_shared/src/README.md

Dictionary: _en_shared_
The idea is to provide a more comprehensive overview of the English
dictionaries and their structure, making it easier for contributors to
understand the purpose of each file and how to contribute effectively.
> -ize words are not American. Americans chose to use them over -ise words, but the truth is that -ize words originated in British English. The Oxford English dictionary prefers -ize over -ise. Which is why the original British English dictionary included -ize variants. 
> _Originally posted by @Jason3S in https://github.com/streetsidesoftware/cspell-dicts/pull/4438#discussion_r2086072643_
> In general, most of the `-ise` words are not correct for US English. If it is an `-ise` word that is used in all variants, then it should be added to …

chore: improve en_shared README files

---

dictionaries/software-terms/src/software-tools.txt

Dictionary: `software-tools.txt`
Add 'helm' and 'helmfile' to software tools dictionary
Not sure if these should go here or in the k8s dictionary.
- https://helm.sh/
- https://helmfile.readthedocs.io

fix: add 'helm' and 'helmfile' to software tools dictionary

---

dictionaries/en_shared/src/shared-additional-words.txt

Dictionary: English All
- `unbundle` - is a common term, often with respect to unbundling telecom packages.
- https://www.merriam-webster.com/dictionary/unbundle
- https://dictionary.cambridge.org/dictionary/english/unbundle

fix: Add `unbundle` to English shared

---

dictionaries/typescript/dict/typescript.txt
dictionaries/typescript/src/typescript.txt

Dictionary: _typescript_
Adds `nodenext` to `typescript`. Similar to https://github.com/streetsidesoftware/cspell-dicts/pull/4095.
- https://www.typescriptlang.org/tsconfig/#node16node18nodenext

fix: add missing 'nodenext' to dict/typescript.txt

---

dictionaries/software-terms/dict/software-tools.txt
dictionaries/software-terms/src/software-tools.txt

Dictionary: _software-tools_
Adds "conventionalcommits"
- conventionalcommits.org
- https://github.com/streetsidesoftware/cspell-dicts/blob/4003ea4fffec78c904a130be9edda880b64b1159/lerna.json#L12

fix: add 'conventionalcommits'

---

dictionaries/de_DE/CHANGELOG.md

Dictionary: de_DE
CHANGELOG entry vor `2.1.0` was malformed (H1 instead of H2) and, therefore, sorted incorrectly to the top. This fixes the changeling by formatting the entry as an H2 (`##`) and sorting the entry to the correct position.
N/A

chore(de_DE): format and sort CHANGELOG entry for 2.1.0 correctly

---

dictionaries/docker/src/docker-words.txt

Dictionary: _Docker_
The verb "to dockerize" is derived from the noun "Docker".
Add dockerizes and dockerizing.
They should not be capitalized as they are not proper nouns, unless
they are at the beginning of a sentence.
For this reason, the words "Dockerize" and "Dockerized" are removed.
- https://github.com/streetsidesoftware/cspell-dicts/pull/4678#issuecomment-3095309135
this follows #4678 PR
- https://github.com/streetsidesoftware/cspell-dicts/pull/4678#issuecomment-3095309135

chore: add dockerizes and dockerizing to dictionaries

---

dictionaries/npm/dict/npm.txt
dictionaries/npm/src/npm.txt

Dictionary:  NPM
Adds lefthook to the npm library
https://lefthook.dev/

fix: add lefthook to npm dictionary

---

dictionaries/en_shared/dict/shared-additional-words.txt
dictionaries/en_shared/src/shared-additional-words.txt
dictionaries/software-terms/dict/softwareTerms.txt
dictionaries/software-terms/src/coding-terms.txt
dictionaries/software-terms/src/software-terms.txt

Added the following two terms:
* `evaluable` - same as the existing `evaluatable`, but a more standard form and more commonly found in dictionaries [1, 2]
* `unpackable` - common coding term for objects that can be unpacked
1. https://www.merriam-webster.com/dictionary/evaluable
2. https://www.oed.com/dictionary/evaluable_adj
3. https://glosbe.com/en/en/evaluable
4. https://glosbe.com/en/en/unpackable

fix: add software terms

---

dictionaries/software-terms/dict/software-tools.txt
dictionaries/software-terms/src/software-tools.txt

Dictionary: `software-tools`
Added `Nushell`, Nushell is a new type of shell.
- <https://www.nushell.sh/>
- `feat:` - for a significant change like adding a whole new set of words to a
dictionary.

fix: add `Nushell` to `software-tools`

---

dictionaries/python/dict/python.txt
dictionaries/python/src/python/python.txt

Added `pyrefly`. Pyrefly is a type checker developed by Meta.
<https://pyrefly.org/>

fix: add `pyrefly` to `python`
